### ISSUE TITLE
Quarterly golang updates (Kubernetes 1.15 through 1.19 (master) branches)

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1134]
### What would you like to be added

Following the discussion on #sig-release Slack, starting [here](https://kubernetes.slack.com/archives/C2C40FMNF/p1582667600068700) and further threaded [here](https://kubernetes.slack.com/archives/C2C40FMNF/p1582668769091500), we're planning the following golang updates:

### Kubernetes 1.19 (`master` branch)

- [x] (@justaugustus) Upgrade to go1.13.9
  - [x] kube-cross bump: https://github.com/kubernetes/release/pull/1200, https://github.com/kubernetes/release/pull/1202
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/679, https://github.com/kubernetes/k8s.io/pull/684
  - [x] k/k bump: https://github.com/kubernetes/kubernetes/pull/89275
  - [x] kubekins/krte variants bump: https://github.com/kubernetes/test-infra/pull/16921, https://github.com/kubernetes/test-infra/pull/16960
  - [x] k/release/k8s-cloud-builder bump: https://github.com/kubernetes/release/pull/1209
  - [x] publishing-bot bump: https://github.com/kubernetes/kubernetes/pull/89500

### Kubernetes 1.18 (`release-1.18` branch)

- [x] (@justaugustus) Begin building/storing kube-cross images on K8s Infra - https://github.com/kubernetes/release/issues/1133, https://github.com/kubernetes/kubernetes/pull/88562
- [x] (@ialidzhikov - https://github.com/kubernetes/kubernetes/pull/87648) Upgrade to go1.13.8
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/610
  - [x] kubekins/krte variants bump: https://github.com/kubernetes/test-infra/pull/16534
  - [x] k/release/k8s-cloud-builder bump: https://github.com/kubernetes/release/pull/1141
- [x] Cherry pick `master` go1.13.9 upgrade: https://github.com/kubernetes/kubernetes/pull/89398

### Kubernetes 1.17 (`release-1.17` branch)

- [x] (@justaugustus - https://github.com/kubernetes/kubernetes/pull/88595) Cherry pick `master` switch to kube-cross on K8s Infra
- [x] (@ialidzhikov - https://github.com/kubernetes/kubernetes/pull/88617) Cherry pick `master` go1.13.8 upgrade
- [x] Cherry pick `master` go1.13.9 upgrade: https://github.com/kubernetes/kubernetes/pull/89399

### Kubernetes 1.16 (`release-1.16` branch)

- [x] (@justaugustus - https://github.com/kubernetes/kubernetes/pull/88595) Cherry pick `master` switch to kube-cross on K8s Infra
- [x] (@ialidzhikov - https://github.com/kubernetes/kubernetes/pull/88618) Cherry pick `master` go1.13.8 upgrade
- [x] Cherry pick `master` go1.13.9 upgrade: https://github.com/kubernetes/kubernetes/pull/89400

### Kubernetes 1.15 (`release-1.15` branch)

- [x] (@justaugustus - https://github.com/kubernetes/kubernetes/pull/88551) Upgrade to go1.12.17
- [x] (@justaugustus - https://github.com/kubernetes/k8s.io/pull/610) Promote `kube-cross:v1.12.17-1`

### Follow ups

- [x] ~(@BenTheElder) k8s.gcr.io kube-cross image pushes~ No longer required now that we build kube-cross on K8s Infra!
- [x] (https://github.com/kubernetes/release/pull/1141) Support targeting `k8s-cloud-builder` container image to kube-cross version
- [ ] (@justaugustus / @cblecker / @liggitt / @BenTheElder / @dims) Document upgrading Golang - https://github.com/kubernetes/release/issues/1139
- [ ] (@kubernetes/release-engineering / @kubernetes/sig-testing) Discuss removing bazel - https://github.com/kubernetes/kubernetes/issues/88553

/assign
/priority critical-urgent

**Comment by justaugustus** [comment]
I'm going to close this out as we're on go1.13.9 for the most recent release branches (1.18 --> 1.16).
Follow-ups are tracked separately at:
- Document upgrading Golang - https://github.com/kubernetes/release/issues/1139
- Update k/k to go1.14.1 - https://github.com/kubernetes/release/issues/1216
- Discuss removing bazel - https://github.com/kubernetes/kubernetes/issues/88553

/close
