### ISSUE TITLE
gh2gcs: Feature/bug tracking

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1320]
### Bug

- [x] Single tags appear to incorrectly upload to the root of `releaseDir` - fixed in https://github.com/kubernetes/release/pull/1470
- [x] Need to cleanup temp dir - fixed in https://github.com/kubernetes/release/pull/1324
- [ ] Copy operation not printing to screen until complete

### Feature

- [x] Add usage documentation - fixed in https://github.com/kubernetes/release/pull/1338
- [x] yaml-based config - fixed in https://github.com/kubernetes/release/pull/1380
- [x] Provide `download-only` option - fixed in https://github.com/kubernetes/release/pull/1337
- [x] (https://github.com/kubernetes/release/pull/1344) Download faster by sending through a channel
- [ ] Do we want to use the -L flag to create manifest logs?
- [ ] Expose certain `GCSCopyOptions` for user configuration
- [ ] --dry-run flag

### Completed in https://github.com/kubernetes/release/pull/1311

- [x] New octal `os.FileMode` format e.g., `0o777`
- [x] Support multiple user-supplied release tags
- [x] Will uploads fail if asset already exists?
- [x] Copies fail when there are no release artifacts
- [x] Remove test flag values

/assign

**Comment by cpanato** [comment]
I'm going to work in the feature `download-only`m if that is ok

**Comment by cpanato** [comment]
i'm going to work in the `Add usage documentation`

**Comment by cpanato** [comment]
maybe one item to add in the list, instead use the shell and `gsutil` we can use the lib to copy, this will remove the dependency to have gsutil installed, but then we need to figure out the access keys. 

if find useful i can make that happen

**Comment by cpanato** [comment]
for this `Expose certain GCSCopyOptions for user configuration` we have the following options defined in the app.

```
var DefaultGCSCopyOptions = &gcs.Options{
	Concurrent:   true,
	Recursive:    true,
	NoClobber:    true,
	AllowMissing: true,
}
```
also the `gsutil cp` have other flags -> https://cloud.google.com/storage/docs/gsutil/commands/cp

which ones do we want to make configurable by the user?

@justaugustus

**Comment by cpanato** [comment]
the bot should not close this :)
/reopen

**Comment by cpanato** [comment]
will work in the `Download faster by sending through a channel`

**Comment by cpanato** [comment]
will try this `Download faster by sending through a channel`

**Comment by justaugustus** [comment]
Thanks for your work here, Carlos!
I'm going to assign this to you and I'd like you to take care of these next (in order of importance):
1. yaml-based config
2. Single tags appear to incorrectly upload to the root of `releaseDir`

/assign @cpanato

**Comment by cpanato** [comment]
I would like to try to complete and close that, so I have a question a couple of questions
1 - Bug:

 > Copy operation not printing to screen until complete

what do we want here? show the copying logs during the upload? not clear this to me

2 - Feature

 > Expose certain GCSCopyOptions for user configuration

which ones do we want to expose?

3 - Feature

> Do we want to use the -L flag to create manifest logs?

4 - Feature

>  --dry-run flag

made a [comment in the past](https://github.com/kubernetes/release/issues/1320#issuecomment-640085790). What is the idea here? the github does not offer this dry run and the gsutil as well, what is the behavior we want?

**Comment by saschagrunert** [comment]
@cpanato do you still consider to work on this? Seems a bit out of scope when comparing to our current roadmap planning…

**Comment by cpanato** [comment]
@saschagrunert I can finish those items, but we need to check if those still needed/make sense otherwise maybe we can close

**Comment by cpanato** [comment]
Ok, did this PR https://github.com/kubernetes/release/pull/1829

I'm not sure about the other items, Please let me know if we want those, or we can close this issue.


@justaugustus @saschagrunert

**Comment by saschagrunert** [comment]
> I'm not sure about the other items, Please let me know if we want those, or we can close this issue.

I'm tending towards closing this issue and re-evaluating the features if they're needed.

**Comment by cpanato** [comment]
@saschagrunert agree

**Comment by cpanato** [comment]
I will close this issue and if we want to add new things or fix any issue we can open a fresh one.

/close
