### ISSUE TITLE
Golang update (go1.14.6 and go1.13.14)

### ISSUE THREAD

**Issue by mkumatag** [kubernetes/release#1410]
**What would you like to be added:**

kubernetes/kubernetes should support go1.14.6

**Why is this needed:**

To include a critical fix for the ppc64le platform, Fix: https://github.com/golang/go/issues/39991
announce: https://groups.google.com/g/golang-announce/c/9KNZ5g9tv4o/m/n_CqeNoUBwAJ
Fixes went in - https://github.com/golang/go/milestone/153?closed=1

Slack mention: https://kubernetes.slack.com/archives/C2C40FMNF/p1594948018000900

**Work items:**

##### Both versions 

- [x] kube-cross bump: https://github.com/kubernetes/release/pull/1411, https://github.com/kubernetes/release/pull/1415
- [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1037
- [x] k/release/k8s-cloud-builder bump: https://github.com/kubernetes/release/pull/1417
- [x] k/k bump (`master`): https://github.com/kubernetes/kubernetes/pull/93198
- [x] k/repo-infra bump: https://github.com/kubernetes/repo-infra/pull/196
- [x] k/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.0.8
- [x] k/k bazel rules_go: https://github.com/kubernetes/kubernetes/pull/93198
- [x] k/k bazel rules_go cherry picks:
    - [x] 1.18: https://github.com/kubernetes/kubernetes/pull/93232
    - [x] 1.17: https://github.com/kubernetes/kubernetes/pull/93233
    - [x] 1.16: https://github.com/kubernetes/kubernetes/pull/93235
- [x] kubekins/krte variants bump: https://github.com/kubernetes/test-infra/pull/18360
- [x] publishing-bot bump: https://github.com/kubernetes/kubernetes/pull/93138

##### go1.13.14-specific items

- [x] k/k bump (`release-1.18`): https://github.com/kubernetes/kubernetes/pull/93232
- [x] Cherry picks:
  - [x] 1.17: https://github.com/kubernetes/kubernetes/pull/93233
  - [x] 1.16: https://github.com/kubernetes/kubernetes/pull/93235
- [x] kubekins/krte variants bump: https://github.com/kubernetes/test-infra/pull/18375

cc: @kubernetes/release-engineering

**Comment by justaugustus** [comment]
This is complete.
/close
