### ISSUE TITLE
Golang 1.15 updates

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1421]
**What would you like to be added:**

Tracking issue for go1.15 updates

**Work items:**

### go1.15beta1

- [x] kube-cross bump: https://github.com/kubernetes/release/pull/1420
- [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1048
- [x] k/k bump (`master`): https://github.com/kubernetes/kubernetes/pull/93264
- [x] k/repo-infra bump: https://github.com/kubernetes/repo-infra/pull/201, https://github.com/kubernetes/repo-infra/pull/202
- [x] k/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.0.9
- [x] k/k bazel rules_go: https://github.com/kubernetes/kubernetes/pull/93264

### go1.15rc1

- [x] kube-cross bump: https://github.com/kubernetes/release/pull/1437
- [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1063
- [x] k/release/k8s-cloud-builder bump: https://github.com/kubernetes/release/pull/1439
- [x] k/k bump (`master`): https://github.com/kubernetes/kubernetes/pull/93264
- [x] k/repo-infra bump: https://github.com/kubernetes/repo-infra/pull/203
- [x] k/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.0.10
- [x] k/k bazel rules_go: https://github.com/kubernetes/kubernetes/pull/93264
- [x] kubekins/krte variants bump: https://github.com/kubernetes/test-infra/pull/18475

### go1.15.0rc2

- [x] kube-cross bump: https://github.com/kubernetes/release/pull/1482
- [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1129
- [x] k/release/k8s-cloud-builder bump: https://github.com/kubernetes/release/pull/1484
- [x] k/repo-infra bump: https://github.com/kubernetes/repo-infra/pull/205
- [x] k/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.0.11
- [x] k/k bump (`master`): https://github.com/kubernetes/kubernetes/pull/93827
  - [x] k/k bazel rules_go: https://github.com/kubernetes/kubernetes/pull/93827
- [x] kubekins/krte variants bump: https://github.com/kubernetes/test-infra/pull/18758

### go1.15.0

- [x] kube-cross bump: https://github.com/kubernetes/release/pull/1487
- [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1138
- [x] k/release/k8s-cloud-builder bump: https://github.com/kubernetes/release/pull/1490
- [x] k/repo-infra bump: https://github.com/kubernetes/repo-infra/pull/206
- [x] k/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.0.11
- [x] k/k bump (`master`): https://github.com/kubernetes/kubernetes/pull/93939
  - [x] k/k bazel rules_go: https://github.com/kubernetes/kubernetes/pull/93939
- [x] kubekins/krte variants bump: https://github.com/kubernetes/test-infra/pull/18806
- [x] publishing-bot bump: https://github.com/kubernetes/kubernetes/pull/93998

### Cherry picks

- [ ] 1.18: https://github.com/kubernetes/kubernetes/pull/94037
- [ ] 1.17: 

cc: @kubernetes/release-engineering @liggitt @dims

**Comment by justaugustus** [comment]
@liggitt -- Let's aggregate the list of update concerns/hotspots to watch here.

**Comment by justaugustus** [comment]
I believe we're waiting on a go1.15rc2, before the official release.
This is still in progress, but in a waiting state at the moment.

**Comment by liggitt** [comment]
looking through the release notes, https://github.com/kubernetes/kubernetes/pull/93797 is needed to unwrap net errors in 1.15

**Comment by justaugustus** [comment]
This is complete outside of the cherry picks, which need to be further discussed.
Carrying that into the go1.15.1 tracking issue: https://github.com/kubernetes/release/issues/1517
/close
