### ISSUE TITLE
[krel] Finish-up krel push

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#1459]
We started migrating from `push-build.sh` to `krel push` in #941 and #1105 but the implementation is not feature complete. We should continue our work here and integrate it into `anago` to have the code being used in production.

- [x] Copy binaries (#1538)
- [x] Writing checksums (#1562)
- [x] Upload artifacts to GCS (#1567)
- [x] Push container images (#1568)
- [x] Push artifacts to release bucket (#1574)
- [x] Add fast build support (#1575)

**Comment by saschagrunert** [comment]
Refers to https://github.com/kubernetes/release/issues/829

**Comment by saschagrunert** [comment]
Done, the integration will be handled separately / in test-infra.
