### ISSUE TITLE
[golang] go1.14.7 and go1.13.15 security updates

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1474]
**What would you like to be added:**

Tracking issue for go1.14.7 and go1.13.15 security updates
Announcement: https://groups.google.com/d/topic/golang-announce/NyPIaucMgXo/discussion

**Work items:**

- [x] kube-cross bump: https://github.com/kubernetes/release/pull/1473
- [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1119
- [x] k/release/k8s-cloud-builder bump: https://github.com/kubernetes/release/pull/1475
- [x] k/repo-infra bump: https://github.com/kubernetes/repo-infra/pull/205
- [x] k/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.0.11
- [x] kubekins/krte variants bump: https://github.com/kubernetes/test-infra/pull/18758
- [ ] publishing-bot bump: https://github.com/kubernetes/kubernetes/pull/93998

### go1.14.7

N/A -- `master` and `release-1.19` are [moving towards go1.15](https://github.com/kubernetes/release/issues/1421)

### go1.13.15

- [x] k/k bump (`release-1.18`): https://github.com/kubernetes/kubernetes/pull/93953
  - [x] k/k bazel rules_go: https://github.com/kubernetes/kubernetes/pull/93953

### Cherry picks

- [x] 1.17: https://github.com/kubernetes/kubernetes/pull/93955
- [x] 1.16: https://github.com/kubernetes/kubernetes/pull/93956

/assign
/area dependency
cc: @kubernetes/release-engineering
