### ISSUE TITLE
Golang 1.15.2 updates

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1517]
**What would you like to be added:**

Tracking issue for go1.15.2 updates
Continuation of https://github.com/kubernetes/release/issues/1421

**Work items:**

### go1.15.1

- [x] kube-cross bump: https://github.com/kubernetes/release/pull/1514
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1205
- [x] go-runner bump: https://github.com/kubernetes/release/pull/1514
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1210
- [x] k/release/k8s-cloud-builder bump: https://github.com/kubernetes/release/pull/1516
- [x] k/repo-infra bump: https://github.com/kubernetes/repo-infra/pull/208
- [x] k/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.1.0

### go1.15.2

- [x] kube-cross image building improvements: https://github.com/kubernetes/release/pull/1418, https://github.com/kubernetes/test-infra/pull/19176
- [x] kube-cross bump: https://github.com/kubernetes/release/pull/1533
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1233
- [ ] go-runner bump: https://github.com/kubernetes/release/pull/1533
  - [ ] image promotion: 
- [x] k/release/k8s-cloud-builder bump: https://github.com/kubernetes/release/pull/1550
- [x] k/repo-infra bump: https://github.com/kubernetes/repo-infra/pull/209
- [x] k/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.1.1
- [x] k/k bump (`master`): https://github.com/kubernetes/kubernetes/pull/94449
  Ensure the following have been updated within the PR:
  - [x] rules_go
  - [x] kube-cross image
  - [ ] go-runner image
  - [x] publishing bot rules
- [x] kubekins/krte variants bump: https://github.com/kubernetes/test-infra/pull/19116

### Cherry picks

- [x] 1.19: https://github.com/kubernetes/kubernetes/pull/94838
- [ ] 1.18: https://github.com/kubernetes/kubernetes/pull/94037
- [ ] 1.17: 

/assign
/area dependency
cc: @kubernetes/release-engineering

**Comment by mkumatag** [comment]
This seems like a never-ending story, I see go 1.15.2 got released last night - https://groups.google.com/g/golang-announce/c/ipD8jvpSFtA/m/B0FcziUVAQAJ

**Comment by justaugustus** [comment]
@mkumatag -- yep, already on it. I'm going to roll it into the k/k PR I have open for go1.15.1.
ref: https://github.com/kubernetes/kubernetes/pull/94449#issuecomment-689852759

**Comment by dims** [comment]
![AlarmingRadiantFirefly-size_restricted](https://user-images.githubusercontent.com/23304/92722879-3c14c880-f336-11ea-8c5c-2687f1379847.gif)

**Comment by dims** [comment]
![WhoppingRepulsiveGrayreefshark-size_restricted](https://user-images.githubusercontent.com/23304/92722991-69617680-f336-11ea-96c2-f4a7c1b85bb9.gif)

**Comment by justaugustus** [comment]
go1.15.3 updates happening here --> https://github.com/kubernetes/release/issues/1651
/close
