### ISSUE TITLE
Golang 1.15.5 updates

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1651]
**What would you like to be added:**

Tracking issue for ~go1.15.3~ go1.15.5 updates
Continuation of https://github.com/kubernetes/release/issues/1517
Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1605129514273400

**Work items:**

### go1.15.5

- [x] kube-cross bump: https://github.com/kubernetes/release/pull/1732
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1423
- [x] go-runner bump: https://github.com/kubernetes/release/pull/1732, https://github.com/kubernetes/release/pull/1752, https://github.com/kubernetes/release/pull/1780

  - [x] The `go-runner:buster-v2.2.0` [job failed](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-go-runner/1327181016887988224).
  
       That job is failing to find an `arm` arch digest for distroless, which I believe is related to distroless going multi-arch (https://github.com/GoogleContainerTools/distroless/pull/600), but not having all of the architectures Kubernetes publishes for ([`ppc64le` example](https://github.com/GoogleContainerTools/distroless/pull/622)).

    - Fixed with https://github.com/GoogleContainerTools/distroless/pull/638. (thanks @mattmoor, @chanseokoh!)
  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1449
- [x] vulndash bump: https://github.com/kubernetes/release/pull/1732
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1423
- [x] releng-ci bump: https://github.com/kubernetes/release/pull/1732
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1423

#### During kube-cross promotion

- [x] k/repo-infra bump: https://github.com/kubernetes/repo-infra/pull/212
- [x] k/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.1.3

#### After kube-cross promotion

- [x] k/k bump (`master`): https://github.com/kubernetes/kubernetes/pull/95776
  
  Ensure the following have been updated within the PR:
  - [x] rules_go
  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  
#### After kubernetes/kubernetes has been updated

- [x] k/release/k8s-cloud-builder bump: https://github.com/kubernetes/release/pull/1784
- [x] kubekins/krte variants bump: https://github.com/kubernetes/test-infra/pull/20038
- [x] k8s-ci-builder variants bump: https://github.com/kubernetes/release/pull/1784 

### go1.15.3

- [x] kube-cross bump: https://github.com/kubernetes/release/pull/1650
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1352 
- [ ] go-runner bump: https://github.com/kubernetes/release/pull/1650
  - [ ] image promotion: 
- [x] k/release/k8s-cloud-builder bump: https://github.com/kubernetes/release/pull/1654
- [x] k/repo-infra bump: https://github.com/kubernetes/repo-infra/pull/210
- [x] k/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.1.2 
- [ ] k/k bump (`master`): https://github.com/kubernetes/kubernetes/pull/95776
  Ensure the following have been updated within the PR:
  - [x] rules_go
  - [x] kube-cross image
  - [ ] go-runner image
  - [x] publishing bot rules
- [ ] kubekins/krte variants bump: 

### Cherry picks

- [ ] 1.19: https://github.com/kubernetes/kubernetes/pull/97246
- [ ] 1.18: https://github.com/kubernetes/kubernetes/pull/94037
- [ ] 1.17: 

/assign
/area dependency
cc: @kubernetes/release-engineering

**Comment by justaugustus** [comment]
This is done.
go1.15.8 updates are being tracked here: https://github.com/kubernetes/release/issues/1895

/close
