### ISSUE TITLE
Dependency update - Golang 1.16

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1834]
### Tracking info

go1.16 was released on 2/16: https://groups.google.com/g/golang-announce/c/q-exD-8mG3w
go1.16rc1 was released on 1/28: https://groups.google.com/g/golang-announce/c/U_FUHY4wuSc
go1.16beta1 was released on 12/17: https://groups.google.com/g/golang-announce/c/2-Rj3P5uRLs

As Kubernetes 1.20 has already been released, we can get started on pulling in the Golang prereleases.

Golang mailing list announcement: 

SIG Release Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1610074100305000

### Pre-work: k/repo-infra updates

- [x] Update k/repo-infra to bazel 3.4.1, rules_go@0.25.1: https://github.com/kubernetes/repo-infra/compare/v0.1.3...v0.2.0
- [x] Update k/k to bazel 3.4.1 and k/repo-infra@v0.2.0: https://github.com/kubernetes/kubernetes/pull/96011

### Work items for `go1.16rc1`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/1882

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1591

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/1882

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1598

- [x] `vulndash` image update: https://github.com/kubernetes/release/pull/1882

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1591

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/1882

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1591

#### During kube-cross image promotion

- [x] kubernetes/repo-infra update: https://github.com/kubernetes/repo-infra/pull/229 **No longer required as bazel has been removed**

- [x] kubernetes/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.2.1 **No longer required as bazel has been removed**

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/98572

  Ensure the following have been updated within the PR:

  - [x] ~rules_go~ **No longer required as bazel has been removed**
  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/1932

- [x] `k8s-ci-builder` image variants update:  https://github.com/kubernetes/release/pull/1932

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/21129

### Cherry picks

N/A

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements

/assign
cc: @kubernetes/release-engineering

**Comment by liggitt** [comment]
cc @kubernetes/sig-scalability @wojtek-t in case there are any scale impacts we should be keeping an eye on

**Comment by wojtek-t** [comment]
There seem to be some regression in early December. We're working with golang folks to figure that out.
@tosi3k - can you please file an issue for that so that it's possible to track it?

**Comment by tosi3k** [comment]
Done: https://github.com/kubernetes/kubernetes/issues/97846.

**Comment by justaugustus** [comment]
(I'll start moving on this again once go1.16rc1 is out. signal: https://github.com/golang/go/issues/43253)

> There seem to be some regression in early December. We're working with golang folks to figure that out.
> @tosi3k - can you please file an issue for that so that it's possible to track it?

@wojtek-t @tosi3k -- Any updates re: this (👇🏾) regression?

> Done: [kubernetes/kubernetes#97846](https://github.com/kubernetes/kubernetes/issues/97846).

**Comment by justaugustus** [comment]
Echoing the scalability update from https://github.com/kubernetes/kubernetes/issues/97846#issuecomment-768468960:

> It seems we're mostly understanding the issue - we're trying to confirm last remaining details.
> 
> But the bottomline is that it doesn't seem to be golang-related - golang seem to be fine.
> 
> We will update the issue once we confirm the remaining details.

and https://github.com/kubernetes/kubernetes/issues/97846#issuecomment-769187674:

> To add a bit more details to it - there were some internal changes which resulted in some underlying machine architecture having much more predictible networking characteristics than others.
> 
> With our jobs requiring high predictability, the recommendation from Google networking engineers was to simply migrate the jobs to new enough architecture (Skylake+) which we did in: [kubernetes/test-infra#20584](https://github.com/kubernetes/test-infra/pull/20584)
> 
> And that fixed our problems.
> 
> Closing this one as addressed.

**Comment by nikhita** [comment]
go 1.16 tripped the publishing-bot: https://github.com/kubernetes/kubernetes/issues/56876#issuecomment-789076331

Looks like it's hitting https://github.com/golang/go/issues/44129 or something similar. I'll take a look at this tomorrow.

**Comment by justaugustus** [comment]
Thanks @nikhita! Keep us posted :)

**Comment by nikhita** [comment]
> Looks like it's hitting golang/go#44129 or something similar. I'll take a look at this tomorrow.

Created to fix this https://github.com/kubernetes/kubernetes/pull/99674

**Comment by justaugustus** [comment]
We're all set here.
go1.16.1 tracking is here: https://github.com/kubernetes/release/issues/1936

/close
