### ISSUE TITLE
Dependency update - Golang 1.15.7

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1851]
### Tracking info

Golang 1.15.7 is a security release scheduled to come out on 1/19.
@kubernetes/release-engineering 
/assign @ameukam @cpanato 
cc: @RobertKielty 

Link to any previous tracking issue: 

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/KvrRblbXp_w, https://groups.google.com/g/golang-announce/c/mperVMGa98w

SIG Release Slack thread:  https://kubernetes.slack.com/archives/C2C40FMNF/p1610736817029800

### Work items for `gox.y.z`

- [x] `kube-cross` image update:  https://github.com/kubernetes/release/pull/1857

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1562

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/1857

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1575

- [x] `vulndash` image update: https://github.com/kubernetes/release/pull/1857

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1563

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/1857

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1564

#### During kube-cross image promotion

- [x] kubernetes/repo-infra update: https://github.com/kubernetes/repo-infra/pull/223

- [x] kubernetes/repo-infra release cut: Not needed the latest release https://github.com/kubernetes/repo-infra/releases/tag/v0.2.0 have the support the go 1.15.7 (https://kubernetes.slack.com/archives/C2C40FMNF/p1611575704030800?thread_ts=1610736817.029800&cid=C2C40FMNF)

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/98363

  Ensure the following have been updated within the PR:

  ~- [ ] rules_go~
  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/1876

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/1876

- [x] `kubekins`/`krte` image variants update:  https://github.com/kubernetes/test-infra/pull/20623

### Cherry picks

- [ ] Kubernetes 1.20: https://github.com/kubernetes/kubernetes/pull/98533 
- [ ] Kubernetes x.y-2: 
- [ ] Kubernetes x.y-3: 

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements

/assign
cc: @kubernetes/release-engineering

**Comment by brandond** [comment]
New releases are out: https://groups.google.com/g/golang-announce/c/mperVMGa98w
* cmd/go: packages using cgo can cause arbitrary code execution at build time
* crypto/elliptic: incorrect operations on the P-224 curve

**Comment by justaugustus** [comment]
We've started up with this update in https://github.com/kubernetes/release/pull/1857, but just noting here that these security updates should be minimally impactful to kubernetes/kubernetes, as @brandond suggested in [Slack](https://kubernetes.slack.com/archives/C2C40FMNF/p1611103121051300?thread_ts=1610736817.029800&cid=C2C40FMNF).

**Comment by justaugustus** [comment]
Golang 1.15.8 has been released.
We'll be tracking any remaining work here: https://github.com/kubernetes/release/issues/1895

/close
