### ISSUE TITLE
Collaborative Release Notes review

### ISSUE THREAD

**Issue by wilsonehusin** [kubernetes/release#1889]
### Intro
[Initial design document](https://docs.google.com/document/d/13SCA5HfjdJy5ZiEMPfhhZ2w25sqMS_QOcsxrJEwSLn4/edit?usp=sharing) was shared to `#release-notes`.

#### What would you like to be added:

Ability for release notes review and workflow to be more collaborative, instead of individuals running the tool and reviewing by themselves.

#### Why is this needed:

Increasing collaboration in team so that work does not happen in isolation

#### Proof of concept (ish?)

Ignoring the code, I have created [a sample of what this can look like](https://github.com/wilsonehusin/relnotesd-test/pull/1). However, instead of having the preview rendered on a comment (which makes the noise to PRs being linked), we can create a dummy repository or deploy to some page over Netlify / GitHub pages.

This means our workflow of reviewing release notes can be clearly seen through PR and commits, linked to each and every step.

#### Prefactor

- [x] reduce API calls to GitHub #1888
- [ ] allow release notes process to pause / continue #2258
- [ ] increase test coverage #2272

... to be determined / continued / discussed ...

**Comment by wilsonehusin** [comment]
/reopen

👋🏼 I'm back, will be updating this with  more actionable steps to make this happen 😄

**Comment by cici37** [comment]
Would you consider to add more test cases for release notes? Seems like lack of test coverage right now^^

**Comment by puerco** [comment]
Most definitely, it is something I've also wanted to do for a long time.

**Comment by cici37** [comment]
Ref: https://github.com/kubernetes/release/issues/2272
