### ISSUE TITLE
Dependency update - Golang 1.15.8

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1895]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/1851

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/rUbPPotvaFM

SIG Release Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1612480925169900

### Work items for `go1.15.8`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/1896

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1611

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/1896

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1610

- [x] `vulndash` image update: https://github.com/kubernetes/release/pull/1896

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1609

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/1896

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1612

#### During kube-cross image promotion

- [x] kubernetes/repo-infra update: https://github.com/kubernetes/repo-infra/pull/228

- [x] kubernetes/repo-infra release cut: https://github.com/kubernetes/repo-infra/tree/v0.1.4

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/98834

  Ensure the following have been updated within the PR:

  - ~[ ] rules_go~
  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: was updated here: https://github.com/kubernetes/release/pull/1896 and the prow jow execution is https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-k8s-cloud-builder/1358062871942008832

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/1899

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/20775

### Cherry picks

- [x] Kubernetes 1.20: https://github.com/kubernetes/kubernetes/pull/98962
- [x] Kubernetes 1.19: https://github.com/kubernetes/kubernetes/pull/99093

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements

/assign @ameukam @cpanato 
cc: @kubernetes/release-engineering
/milestone v1.21

**Comment by cpanato** [comment]
all work for this update is done! 🚀 

/close
