### ISSUE TITLE
Dependency update - Golang 1.16.1 (security update)

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1936]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/1834

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/UERZo89zw8o

SIG Release Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1615216589218000

### Work items for `go1.16.1`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/1937

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1774

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/1937

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1774

- [x] `vulndash` image update: https://github.com/kubernetes/release/pull/1937

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1774

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/1937

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1774

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/100106

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/1941

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/1941

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/21302

### Cherry picks

N/A

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements

/assign
cc: @kubernetes/release-engineering

FYI @kubernetes/release-team, as this will land after v1.21 Code Freeze is announced.

**Comment by justaugustus** [comment]
All set here.
/close
