### ISSUE TITLE
Dependency update - Golang 1.15.10

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1940]
### Tracking info

Link to any previous tracking issue: 

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/MfiLYjG-RAw

SIG Release Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1615405842039400

### Work items for `go1.15.10`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/1946

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1785

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/1946

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1784

- [x] `vulndash` image update: N/A

  
  - [x] image promotion: N/A

- [x] `releng-ci` image update: N/A

  
  - [x] image promotion: N/A

#### During kube-cross image promotion

- [x] kubernetes/repo-infra update: https://github.com/kubernetes/repo-infra/pull/230

- [x] kubernetes/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.1.5

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`release-1.20`): https://github.com/kubernetes/kubernetes/pull/100375

  Ensure the following have been updated within the PR:

  - [x] rules_go
  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [ ] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/1973

- [ ] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/1973

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/21496

### Cherry picks

- [x] Kubernetes 1.19: https://github.com/kubernetes/kubernetes/pull/100520

### Follow-up items

- [x] Ensure the Golang issue template is updated with any new requirements

### Work items for `go1.15.9`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/1942

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1778

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/1942

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1777

- [x] `vulndash` image update: N/A

  
  - [x] image promotion: N/A

- [x] `releng-ci` image update: N/A

  
  - [x] image promotion: N/A

/help
cc: @kubernetes/release-engineering

**Comment by cpanato** [comment]
@justaugustus i can work on that tomorrow my morning

Tgis is applied for release-1.19 and 1.20 rigth?

**Comment by cpanato** [comment]
work is done
/close
