### ISSUE TITLE
Dependency update - Golang 1.15.11

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#1984]
### Tracking info

Link to any previous tracking issue: 

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/wVRzkWSQpO0

SIG Release Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1617365695206200

### Work items for `go1.15.11`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/1985

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1869

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/1985

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1868

- [x] `vulndash` image update: N/A

  
  - [x] image promotion:  N/A

- [x] `releng-ci` image update:  N/A

  
  - [x] image promotion: N/A

#### During kube-cross image promotion

- [x] kubernetes/repo-infra update: https://github.com/kubernetes/repo-infra/pull/234
- [x] kubernetes/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.1.6

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`1.20`): https://github.com/kubernetes/kubernetes/pull/101192

  Ensure the following have been updated within the PR:

  - [x] rules_go
  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2009

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2009

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/21844

### Cherry picks

- [x] Kubernetes 1.19: https://github.com/kubernetes/kubernetes/pull/101197 

### Follow-up items

/assign @cpanato 
cc: @kubernetes/release-engineering

**Comment by cpanato** [comment]
All work is done
/close
