### ISSUE TITLE
Dependency update - Golang 1.16.3

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#2005]
### Tracking info

Link to any previous tracking issue: 

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/wVRzkWSQpO0

SIG Release Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1618545755031100

### Work items for `go1.16.3`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2006, https://github.com/kubernetes/release/pull/2007

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1944

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2006, https://github.com/kubernetes/release/pull/2007

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1944

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2006, https://github.com/kubernetes/release/pull/2007

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1944

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/101206

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2008

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2008

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/21839

### Cherry picks

- [x] Kubernetes 1.21: https://github.com/kubernetes/kubernetes/pull/101209

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] 

/assign
cc: @kubernetes/release-engineering

**Comment by justaugustus** [comment]
Update PRs complete.
kubekins-e2e and krte image bumps will get picked up next week in the autobump PR approvals for test-infra.

/close

**Comment by tao12345666333** [comment]
We have just released Go versions 1.16.4 and 1.15.12, minor point releases.

This minor release includes a security fix according to the new security policy (#44918).

ReadRequest and ReadResponse in net/http can hit an unrecoverable panic when reading a very large header (over 7MB on 64-bit architectures, or over 4MB on 32-bit ones). Transport and Client are vulnerable and the program can be made to crash by a malicious server. Server is not vulnerable by default, but can be if the default max header of 1MB is overridden by setting Server.MaxHeaderBytes to a higher value, in which case the program can be made to crash by a malicious client.

This also affects golang.org/x/net/http2/h2c and HeaderValuesContainsToken in golang.org/x/net/http/httpguts, and is fixed in golang.org/x/n...@v0.0.0-20210428140749-89ef3d95e781.

This is issue [#45710](https://github.com/golang/go/issues/45710) and CVE-2021-31525.

Should we update Golang to 1.16.4? It's a security fix version.

**Comment by justaugustus** [comment]
> Should we update Golang to 1.16.4? It's a security fix version.

Thanks @tao12345666333! Tracking this work here: https://github.com/kubernetes/release/issues/2060
