### ISSUE TITLE
hyperkube removal tracking (after v1.18 EOL)

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#2017]
The next v1.18 release (v1.18.19) on 5/7/21 will bring v1.18 to End of Life: https://github.com/kubernetes/sig-release/pull/1532
With that, we'll need to remove any remaining references to hyperkube.

This issue tracks that work.

- [x] Remove debian-hyperkube-base image building:
  - [x] https://github.com/kubernetes/release/pull/2018
  - [x] https://github.com/kubernetes/test-infra/pull/21941
- [x] `area/hyperkube` label: https://github.com/kubernetes/test-infra/pull/21941
- [x] gcb/build prototype jobs: https://github.com/kubernetes/release/pull/2019
- [ ] Remove hyperkube from subproject listing: https://github.com/kubernetes/community/pull/5850

**Comment by BenTheElder** [comment]
cc @dims

**Comment by justaugustus** [comment]
Last piece: https://github.com/kubernetes/community/pull/5850
/assign
/area release-eng hyperkube
/sig release
/kind cleanup
