### ISSUE TITLE
Dependency update - Golang 1.16.4 / 1.15.12

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#2060]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2005#issuecomment-834174908
(FYI @tao12345666333)

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/cu9SP4eSXMc

SIG Release Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1620388464296500

### Work items for `go1.16.4` / `go1.15.12`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2059

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2015

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2059

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2015

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2059

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2015

#### During kube-cross image promotion 

- [x] kubernetes/repo-infra update `go1.16`: N/A
- [x] kubernetes/repo-infra update `go1.15`: https://github.com/kubernetes/repo-infra/pull/240 

- [x] kubernetes/repo-infra release cut `go1.15`: https://github.com/kubernetes/repo-infra/releases/tag/v0.1.7

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`) `go1.16`: https://github.com/kubernetes/kubernetes/pull/101809

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2061

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2061

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/22121

### Cherry picks

- [x] Kubernetes 1.21: https://github.com/kubernetes/kubernetes/pull/101811

---

- [x] kubernetes/kubernetes update (`1.20` / `1.19`) `go1.15`: https://github.com/kubernetes/kubernetes/pull/101845

  Ensure the following have been updated within the PR: 

  - [x] rules_go
  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

### Cherry picks

- [x] Kubernetes 1.19: https://github.com/kubernetes/kubernetes/pull/101846

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: (go1.15) https://github.com/kubernetes/release/pull/2063

- [x] `k8s-ci-builder` image variants update: (go1.15) https://github.com/kubernetes/release/pull/2063

- [x] `kubekins`/`krte` image variants update: (go1.15) https://github.com/kubernetes/test-infra/pull/22155

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements

/assign
cc: @kubernetes/release-engineering

**Comment by justaugustus** [comment]
> @justaugustus are you doing to handle both updates or want to split the efforts?

@cpanato -- I'll work on go1.16.4. Can you work on go1.15.12 once the images from https://github.com/kubernetes/release/pull/2059 get promoted?

/assign @cpanato

**Comment by cpanato** [comment]
@justaugustus roger that!

**Comment by cpanato** [comment]
all work is done

/close
