### ISSUE TITLE
Dependency update - Golang 1.16.5 / 1.15.13

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2107]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2060 

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/RgCMkAEQjSI/m/r_EP-NlKBgAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1623076353251200

### Work items for `go1.16.5` / `go1.15.13`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2111

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2158

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2111

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2158

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2111

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2158

#### During kube-cross image promotion

- [x] kubernetes/repo-infra update `go1.16`: N/A
- [x] kubernetes/repo-infra update `go1.15`: https://github.com/kubernetes/repo-infra/pull/241

- [x] kubernetes/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.1.8

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/102689

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2116

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2116

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/22516

### Cherry picks

- [x] Kubernetes 1.21: https://github.com/kubernetes/kubernetes/pull/102739
---

### For k8s releases 1.19 and 1.20 which uses go1.15.x

- [x] kubernetes/kubernetes update (`1.20`) `go1.15`: https://github.com/kubernetes/kubernetes/pull/102786

  Ensure the following have been updated within the PR: 

  - [x] rules_go
  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

### Cherry picks

- [x] Kubernetes 1.19: https://github.com/kubernetes/kubernetes/pull/102809

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: (go1.15) https://github.com/kubernetes/release/pull/2122

- [x] `k8s-ci-builder` image variants update: (go1.15) https://github.com/kubernetes/release/pull/2122

- [x] `kubekins`/`krte` image variants update: (go1.15)  https://github.com/kubernetes/test-infra/pull/22564

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements

/assign
cc: @kubernetes/release-engineering

**Comment by thejoycekung** [comment]
PR to update 1.19 with go1.15.13: https://github.com/kubernetes/kubernetes/pull/102809

**Comment by justaugustus** [comment]
It looks like we're all squared away here.
Thanks @thejoycekung and @cpanato! 🎉 

/close
