### ISSUE TITLE
Dependency update - Golang 1.16.6 / 1.15.14

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#2157]
### Tracking info

Link to any previous tracking issue: #2107

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/JvWG9FUUYT0/m/VK1iHZosAgAJ

#release-management Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1626164119119300

### Work items for `go1.16.6`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2162

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2331

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2162

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2331

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2162

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2331

#### During kube-cross image promotion

- [x] kubernetes/repo-infra update: https://github.com/kubernetes/repo-infra/pull/242

- [x] kubernetes/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.1.9

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/103669

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2163

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2166

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/22878

### Cherry picks

- [x] Kubernetes 1.21: https://github.com/kubernetes/kubernetes/pull/103670

---

### For k8s releases 1.19 and 1.20 which uses go1.15.x

- [x] kubernetes/kubernetes update (`1.20`) `go1.15`: https://github.com/kubernetes/kubernetes/pull/103677

  Ensure the following have been updated within the PR: 

  - [x] rules_go
  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

### Cherry picks

- [x] Kubernetes 1.19: https://github.com/kubernetes/kubernetes/pull/103705

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: (go1.15) https://github.com/kubernetes/release/pull/2171

- [x] `k8s-ci-builder` image variants update: (go1.15) https://github.com/kubernetes/release/pull/2171

- [x] `kubekins`/`krte` image variants update: (go1.15)   https://github.com/kubernetes/test-infra/pull/22899

### Follow-up items

- [ ] We need to establish a mechanism to bump the test images in the jobs once we bump the kubekins image. During the July '21 patches, we bumped the golang version in kubekins but did not update the jobs and ran the release based on signal from the outdated image. Ref: https://github.com/kubernetes/test-infra/issues/21137  

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] 

/assign @xmudrii @verolop
cc: @kubernetes/release-engineering

**Comment by mengjiao-liu** [comment]
/assign
I wanted to try this work to see the process of updating the Go image.

**Comment by justaugustus** [comment]
This should be complete / is already superseded by https://github.com/kubernetes/release/issues/2196.
/close
