### ISSUE TITLE
Dependency update - Golang 1.17

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#2169]
### Tracking info

Link to any previous tracking issue: N/A

Golang mailing list announcement:

- go1.17: https://groups.google.com/g/golang-announce/c/wB1fph5RpsE
- go1.17rc2: https://groups.google.com/g/golang-announce/c/yk30ovJGXWY
- go1.17rc1: https://groups.google.com/g/golang-announce/c/gJE7OtHlRbM

SIG Release Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1626226473096200

---

### Work items for `go1.17rc1`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2117
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2337
- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2117
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2337
- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2117
- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2168

#### After kube-cross image promotion

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2168
- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/22887

---

### Work items for `go1.17rc2`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2188
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2459
- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2188
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2459
- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2188
- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2188

#### After kube-cross image promotion

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2190
- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/23139

---

### Work items for `go1.17`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2211
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2608
- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2211
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2608
- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2211

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/103692

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2222
- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2211
- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/23354

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] 

/assign
cc: @kubernetes/release-engineering

**Comment by justaugustus** [comment]
FYI for go1.17 tracking. 
No plan on landing this in kubernetes/kubernetes until after 1.22.0 has been been released.

cc: @thockin @liggitt @dims @kubernetes/sig-scalability

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/100895 needs to be resolved before updating to go1.17

**Comment by justaugustus** [comment]
Notice sent to k-dev: https://groups.google.com/g/kubernetes-dev/c/F_jcnGZtNas
Nice work, everyone!
/close

**Comment by rifelpet** [comment]
I see the kubekins-e2e `experimental` image variant is still on go 1.16. Is that intentional or will that be updated to 1.17 at some point?

https://github.com/kubernetes/test-infra/blob/ce880de448fef7145649d682353dfa80f4b542d2/images/kubekins-e2e/variants.yaml#L4
