### ISSUE TITLE
Dependency update - Golang 1.16.7 / 1.15.15

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2196]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2157

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/uHACNfXAZqk/m/46sU9AeUAAAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1628235574145600

### Work items for `go1.16.7` / `go1.15.15`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2197

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2478

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2197

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2478

- [x] `vulndash` image update: https://github.com/kubernetes/release/pull/2197

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2197

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2478

#### During kube-cross image promotion

- [x] kubernetes/repo-infra update: https://github.com/kubernetes/repo-infra/pull/243

- [x] kubernetes/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.1.10

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/104199

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2198

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2198

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/23172

### Cherry picks

- [x] Kubernetes 1.22: https://github.com/kubernetes/kubernetes/pull/104200
- [x] Kubernetes 1.21:  https://github.com/kubernetes/kubernetes/pull/104201

---

### For k8s releases 1.19 and 1.20 which uses go1.15.x

- [x] kubernetes/kubernetes update (`1.20`) `go1.15`: https://github.com/kubernetes/kubernetes/pull/104215

  Ensure the following have been updated within the PR: 

  - [x] rules_go
  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

### Cherry picks

- [x] Kubernetes 1.19: https://github.com/kubernetes/kubernetes/pull/104216

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: (go1.15) https://github.com/kubernetes/release/pull/2200

- [x] `k8s-ci-builder` image variants update: (go1.15) https://github.com/kubernetes/release/pull/2200

- [x] `kubekins`/`krte` image variants update: (go1.15)  https://github.com/kubernetes/test-infra/pull/23175

- [x] update staging/publishing bot rules: https://github.com/kubernetes/kubernetes/pull/104226

### Follow-up items

- [x] Update GH issue template to add staging/publishing bot rules step: https://github.com/kubernetes/release/pull/2201

/assign
cc: @kubernetes/release-engineering

**Comment by justaugustus** [comment]
@cpanato -- As part of this issue, we should update the template to include a task for ensuring the go version for older releases is up-to-date for staging/publishing bot rules.

Example: https://github.com/kubernetes/kubernetes/pull/104226
FYI @kubernetes/publishing-bot-reviewers

**Comment by cpanato** [comment]
@justaugustus yep, I was waiting for the 1.19/1.20 get merged to open this PR, will add in the issue template

**Comment by justaugustus** [comment]
This looks complete.
/close
