### ISSUE TITLE
Dependency update - Golang 1.17.1 /1.16.8

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2238]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2196

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/dx9d7IOseHw/m/KNH37k37AAAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1631260764156400

### Work items for `go1.17.1` / `go1.16.8`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2239

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2696

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2239

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2696

- [x] `vulndash` image update: https://github.com/kubernetes/release/pull/2239

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2239

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/2696

#### During kube-cross image promotion

- [x] kubernetes/repo-infra update: N/A those release branches / main branch does not use repo-infra anymore

- [x] kubernetes/repo-infra release cut: N/A those release branches / main branch does not use repo-infra anymore

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/104904

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2246

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2246

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/23592

### Cherry picks

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/105040

---

### For k8s releases 1.21 and 1.22 which uses go1.16.x

- [x] kubernetes/kubernetes update (`1.22`) `go1.16`: https://github.com/kubernetes/kubernetes/pull/104905

  Ensure the following have been updated within the PR: 

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

### Cherry picks

- [x] Kubernetes 1.21: https://github.com/kubernetes/kubernetes/pull/104906

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: (go1.16) https://github.com/kubernetes/release/pull/2252

- [x] `k8s-ci-builder` image variants update: (go1.16) https://github.com/kubernetes/release/pull/2252

- [x] `kubekins`/`krte` image variants update: (go1.16)  https://github.com/kubernetes/test-infra/pull/23608

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements

/assign
cc: @kubernetes/release-engineering
