### ISSUE TITLE
[Placeholder] Dependency update - Golang 1.17.2 /1.16.9

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2254]
When we have new go updates for 1.17 and 1.16, Ww have a task to update the tag image for kube-cross in the release-1.21 branch to use a kube-cross with the appropriate tag for that branch, to follow the pattern of the others

### Tracking info

Link to any previous tracking issue: 

Golang mailing list announcement: 

SIG Release Slack thread: 

### Work items for `gox.y.z`

- [ ] `kube-cross` image update: 
- [ ] update kube-cross to build images for 1.21 and 1.22 release branches as well (https://github.com/kubernetes/kubernetes/pull/104906#issuecomment-920095463)

  
  - [ ] image promotion: 

- [ ] `go-runner` image update: 

  
  - [ ] image promotion: 

- [ ] `vulndash` image update: 

  
  - [ ] image promotion: 

- [ ] `releng-ci` image update: 

  
  - [ ] image promotion: 

#### During kube-cross image promotion

- [ ] kubernetes/repo-infra update: 

- [ ] kubernetes/repo-infra release cut: 

#### After kube-cross image promotion

- [ ] kubernetes/kubernetes update (`master`): 

  Ensure the following have been updated within the PR:

  - [ ] rules_go
  - [ ] kube-cross image
  - [ ] go-runner image
  - [ ] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [ ] `k8s-cloud-builder` image update: 

- [ ] `k8s-ci-builder` image variants update: 

- [ ] `kubekins`/`krte` image variants update: 

### Cherry picks

- [ ] Kubernetes x.y-1: 
- [ ] Kubernetes x.y-2: 
- [ ] Kubernetes x.y-3: 

- [ ] publishing bot rule updates for active Golang versions: 

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] 

/assign @cpanato @justaugustus 
cc: @kubernetes/release-engineering

**Comment by cpanato** [comment]
Pre announcement for the go patch releases: https://groups.google.com/g/golang-announce/c/7efr4VBoZIw/m/fr7mKcx8BAAJ?utm_medium=email&utm_source=footer

**Comment by mengjiao-liu** [comment]
Go versions 1.17.2 and 1.16.9 have been released.
see https://groups.google.com/g/golang-announce/c/AEBu9j7yj5A

/assign

**Comment by cpanato** [comment]
all work is done
thanks @mengjiao-liu 

/close
