### ISSUE TITLE
SLSA Level 1 compliance in the Kubernetes Release Process

### ISSUE THREAD

**Issue by puerco** [kubernetes/release#2267]
## Justification and Goal

Building on the [SIG Release roadmap and vision](https://github.com/kubernetes/sig-release/blob/master/roadmap.md) strategy, we would like to ensure that our release process is fully [SLSA](https://slsa.dev/) compliant. Our north star vision document calls to _"establish a consumable, introspectable, and secure supply chain for Kubernetes"_ and Release Engineering would like to frame and adopt the SLSA requirements as a guide to secure our process and artifacts.

In the short term, the first goal of this project will be to achieve SLSA 1 compliance. Based on an initial assessment, we are close (see spreadsheet linked bellow). Most of the work required centers around providing provenance metadata while other areas can reach compliance with minor adjustments.

SLSA compliance checklist: https://docs.google.com/spreadsheets/d/1fNdJJZZdEJAJU0ZaCnYcIlZA3L-bwT7vY7ZesqW3WEs/edit?usp=sharing

The following work items should be completed to make the Kubernetes release process SLSA compliant:

## Provenance Metadata

To provide the provenance metadata needed to be SLSA compliant, we need to work on tooling which needs to be plugged into the release process (anago/krel) and into the Container Image Promoter.

### Artifacts Stored in the Release Bucket

This list includes the binaries, source, tarballs, release notes, etc.

- [x] Make the necessary build environment information available to the release process. We should be able to read the relevant data from the git repository, the GCB environment, invocation data from `krel`. https://github.com/kubernetes/release/pull/2273
- [x] Create the necessary code to produce the provenance attestation. https://github.com/kubernetes/release/pull/2273 Namely, we need to:
    - Be able to write in-toto attestations with
    - SLSA predicates
    - Add the necessary logic to read artifacts and add them as subjects in the attestation
- [x] Add logic to clone the predicate of an in-toto attestation into a new statement #2283
- [x] Add a new phase to `anago/stage` to generate the provenance metadata with the data described above https://github.com/kubernetes/release/pull/2273
- [x] Write the attestation file and persist it in the staging bucket https://github.com/kubernetes/release/pull/2273
- [x] Read the provenance metadata at the start of `anago/release` #2283
- [x] Use the metadata to verify the staged artifacts #2283
- [x] Clone the predicate and reuse it to bootstrap the final provenance attestation(s) #2283
- [x] Populate the new provenance documents with data from the artifacts in each release. For this step, we can look to see if it is possible to incorporate each release's SBOM as an SPDX predicate.   #2300
- [x] Write the provenance files to the release bucket along with the other artifacts. #2300

### Additional Attestations to be Published Along Container Images

To attest to the provenance of our container images, we need to do some more advances to the image promoter. The following is an initial proposal:

- [ ] When pushing images to the staging repository, extract the SLSA predicate from the attestation produced at the end of staging.
- [ ] Use the cosign libraries to generate a new attestation that includes the krel predicate. One for each image and push it to the staging repo. 
- [ ] Before image promotion starts, verify the provenance metadata stored in the registry with the images.
- [ ] After image promotion, clone the SLSA predicate from the pre-promotion registry. 
- [ ] Reuse it to generate a new attestation for the promoted image.
 [ ] Use cosign to finalize the attestation and upload it to the registry along the final image

**Comment by dlorenc** [comment]
> * [ ]  Use the cosign libraries to generate a new attestation that includes the krel predicate. One for each image and push it to the staging repo.
> *

cc @dekkagaijin @mattmoor @n3wscott for this one. The new cosign libraries are coming along great!

**Comment by justaugustus** [comment]
@kubernetes/release-engineering -- FYI that SLSA provenance v0.2 is out and our tooling should be updated to conform to that https://slsa.dev/provenance/v0.2.

See https://github.com/slsa-framework/slsa/blob/main/docs/provenance/v0.2.md#migrating-from-01 for details.

**Comment by puerco** [comment]
@justaugustus  I have been tracking the road to 0.2 and I have that in the works already. But I want to merge #2300 first to complete the chain and PR the format change by itself.

**Comment by matglas** [comment]
@puerco is the tooling not up to SLSA Level 1 at this point? Maybe the additional tasks need to move to the new SLSA Level 3 issue.

**Comment by saschagrunert** [comment]
@puerco do you mind closing this one in favor of the enhancement https://github.com/kubernetes/enhancements/issues/3027 ?

**Comment by puerco** [comment]
OK, yeah let's close this as we have the KEP now.
/close
