### ISSUE TITLE
Dependency update - Golang 1.17.3 /1.16.10

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2304]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2254

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/0fM21h43arc/m/a2Hu_dWRAAAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1636047728086300

### Work items for `go1.17.3`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2305

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3043

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2305

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3043

- [x] `vulndash` image update: https://github.com/kubernetes/release/pull/2305

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3043

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2305

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3043

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/106209

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2306

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2306

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/24273

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/106217

---

### For k8s releases 1.21 and 1.22 which uses go1.16

- [x] kubernetes/kubernetes update (`1.22`) `go1.16`: https://github.com/kubernetes/kubernetes/pull/106223

  Ensure the following have been updated within the PR: 

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

### Cherry picks

- [x] Kubernetes 1.21: https://github.com/kubernetes/kubernetes/pull/106224

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: (go1.16) https://github.com/kubernetes/release/pull/2311

- [x] `k8s-ci-builder` image variants update: (go1.16) https://github.com/kubernetes/release/pull/2311

- [x] `kubekins`/`krte` image variants update: (go1.16) https://github.com/kubernetes/test-infra/pull/24306

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] 

/assign
cc: @kubernetes/release-engineering

**Comment by cpanato** [comment]
all the work is done

/close
