### ISSUE TITLE
Dependency update - Golang 1.18.0

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#2307]
### Tracking info

Golang mailing list announcement:

- go1.18beta1: https://groups.google.com/g/golang-announce/c/eAjK4Oezs_A
- go1.18beta2: https://groups.google.com/g/golang-announce/c/O0BMo6p-R4c/m/PYbHugytAQAJ
- go1.18rc1: https://groups.google.com/g/golang-announce/c/QHL1fTc352o
- go1.18: https://groups.google.com/g/golang-announce/c/6gJm7mgF6rw

SIG Release Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1639512934157200

golang net/netip package coming in Go 1.18: https://github.com/kubernetes/kubernetes/issues/106161

### Work items for `go1.18`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2464

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3538

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2464

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3538

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2464

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3539

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/108870

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image

#### After kubernetes/kubernetes (`master`) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2472

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2472

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/25723

### Work items for `go1.18rc1`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2433

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3425

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2433

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3425

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2433

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/107105

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2437

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2433

- [x] `kubekins`/`krte` image variants update: 
  - [x] `go-canary` variant: https://github.com/kubernetes/test-infra/pull/25346
  - [x] Update go-canary presubmits to use go1.18rc1 images: https://github.com/kubernetes/test-infra/pull/25349

### Work items for `go1.18beta2`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2411

  
  - [x] image promotion:  https://github.com/kubernetes/k8s.io/pull/3363

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2411

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3364

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2411

### Work items for `go1.18beta1`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2370

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3211

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2370

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3214

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2370

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2371

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2370

- [x] `kubekins`/`krte` image variants update: 
  - [x] `go-canary` variant: https://github.com/kubernetes/test-infra/pull/24704
  - [x] Update go-canary presubmits to use go1.18beta1 images: https://github.com/kubernetes/test-infra/pull/24705

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

/assign
cc: @kubernetes/release-engineering

**Comment by cpanato** [comment]
### Work items for `go1.18beta2`


- [ ] `kube-cross` image update: 

  
  - [ ] image promotion:  


- [ ] `go-runner` image update: 

  
  - [ ] image promotion: https://github.com/kubernetes/k8s.io/pull/3214


- [ ] `releng-ci` image update: 

#### After kube-cross image promotion


- [ ] kubernetes/kubernetes update (`master`): 

  Ensure the following have been updated within the PR:

  - [ ] kube-cross image
  - [ ] go-runner image
  - [ ] publishing bot rules

#### After kubernetes/kubernetes has been updated


- [ ] `k8s-cloud-builder` image update: 


- [ ] `k8s-ci-builder` image variants update: 


- [ ] `kubekins`/`krte` image variants update: 
  - [ ] `go-canary` variant:
  - [ ] Update go-canary presubmits to use go1.18beta2 images: 
  - [ ] `master` variant:

**Comment by MadhavJivrajani** [comment]
fyi - https://github.com/kubernetes/kubernetes/issues/108357#issuecomment-1073731790

**Comment by justaugustus** [comment]
Closing this and filed https://github.com/kubernetes/release/issues/2487 to assess some hiccups in the rollout this time around.
