### ISSUE TITLE
Dependency update - Golang 1.17.4 /1.16.11

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2341]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2304

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/Xcefh1Tfj-U

SIG Release Slack thread: 

### Work items for `go1.17.4`

- [ ] `kube-cross` image update: 

  
  - [ ] image promotion: 

- [ ] `go-runner` image update: 

  
  - [ ] image promotion: 

  
  - [ ] image promotion: 

- [ ] `releng-ci` image update: 

  
  - [ ] image promotion: 

#### After kube-cross image promotion

- [ ] kubernetes/kubernetes update (`master`): 

  Ensure the following have been updated within the PR:

  - [ ] kube-cross image
  - [ ] go-runner image
  - [ ] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [ ] `k8s-cloud-builder` image update: 

- [ ] `k8s-ci-builder` image variants update: 

- [ ] `kubekins`/`krte` image variants update: 

### Cherry picks

- [ ] Kubernetes x.y-1: 
- [ ] Kubernetes x.y-2: 
- [ ] Kubernetes x.y-3: 

- [ ] publishing bot rule updates for active Golang versions: 

---

### For k8s releases 1.21 and 1.22 which uses go1.16

- [ ] kubernetes/kubernetes update (`1.22`) `go1.16`: 

  Ensure the following have been updated within the PR: 

  - [ ] kube-cross image
  - [ ] go-runner image
  - [ ] publishing bot rules

### Cherry picks

- [ ] Kubernetes 1.21: 

#### After kubernetes/kubernetes has been updated

- [ ] `k8s-cloud-builder` image update: (go1.16) 

- [ ] `k8s-ci-builder` image variants update: (go1.16) 

- [ ] `kubekins`/`krte` image variants update: (go1.16) 

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] 

/assign
cc: @kubernetes/release-engineering

**Comment by justaugustus** [comment]
Remaining item is the publishing-bot rule updates: https://github.com/kubernetes/kubernetes/pull/106944
This issue has been superseded by https://github.com/kubernetes/release/issues/2349.
/close
