### ISSUE TITLE
Dependency update - Golang 1.17.5 /1.16.12

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2349]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2341

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/hcmEScgc00k/m/ZWnOjeY4CQAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1639062835057200

### Work items for `go1.17.5`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2351

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3169

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2351

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3169

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2351

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3169

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/106956

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2353

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2353

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/24653

### Cherry picks

- [x] Kubernetes 1.23: https://github.com/kubernetes/kubernetes/pull/106835

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/106944

---

### For k8s releases 1.21 and 1.22 which uses go1.16

- [x] kubernetes/kubernetes update (`1.22`) `go1.16`: https://github.com/kubernetes/kubernetes/pull/106982

  Ensure the following have been updated within the PR: 

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules

### Cherry picks

- [x] Kubernetes 1.21: https://github.com/kubernetes/kubernetes/pull/106983

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: (go1.16) https://github.com/kubernetes/release/pull/2356

- [x] `k8s-ci-builder` image variants update: (go1.16) https://github.com/kubernetes/release/pull/2356

- [x] `kubekins`/`krte` image variants update: (go1.16) https://github.com/kubernetes/test-infra/pull/24653

### Follow-up items

- [x] https://github.com/kubernetes/kubernetes/pull/106949
- [x] https://github.com/kubernetes/kubernetes/pull/106960
- [x] https://github.com/kubernetes/kubernetes/pull/106961
- [ ] Ensure the Golang issue template is updated with any new requirements:

/assign
cc: @kubernetes/release-engineering

**Comment by liggitt** [comment]
I think we also need to update https://github.com/golang/net since that's the source and fix of the CVE (golang vendors golang.org/x/net)

**Comment by cpanato** [comment]
all work is done
/close
