### ISSUE TITLE
Dependency update - Golang 1.17.6 / 1.16.13

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#2379]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2349

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/95ZD3rKn4DI

SIG Release Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1641519008009900

### Work items for `gox.y.z`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2381

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3268

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2381

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3268

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2381

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3268

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`):  https://github.com/kubernetes/kubernetes/pull/107612

  Ensure the following have been updated within the PR:
  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2393

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2393

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/24909

### Cherry picks

- [x] Kubernetes 1.23: https://github.com/kubernetes/kubernetes/pull/107613

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/107616

### For Kubernetes 1.22 and 1.21

- [x] kubernetes/kubernetes update (`master`):  https://github.com/kubernetes/kubernetes/pull/107614
  Ensure the following have been updated within the PR:
  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image

#### Cherry-picks

- [x] Kubernetes 1.21: https://github.com/kubernetes/kubernetes/pull/107615

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2395

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2395

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/24909

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

**Comment by justaugustus** [comment]
@kubernetes/release-engineering -- anyone interested in taking this?

**Comment by palnabarun** [comment]
All PRs merged! 🎉 

/close
