### ISSUE TITLE
Dependency update - Golang 1.17.7 / 1.16.14

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#2425]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2379

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/SUsQn0aSgPQ/m/gx45t8JEAgAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1644535188683299

### Work items for `gox.y.z`

- [x] `kube-cross` image update: #2426

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3389

- [x] `go-runner` image update: #2426

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3389

- [x] `releng-ci` image update: #2426

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3389

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/108091

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2428

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2428

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/25239

### Cherry picks

- [x] Kubernetes 1.23: https://github.com/kubernetes/kubernetes/pull/108100
- [x] Kubernetes 1.22: https://github.com/kubernetes/kubernetes/pull/108101
- [x] Kubernetes 1.21: https://github.com/kubernetes/kubernetes/pull/108102

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/108103

#### After kubernetes/kubernetes has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2429

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2429

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/25239

### Follow-up items

- [x] Ensure the Golang issue template is updated with any new requirements: https://github.com/kubernetes/release/pull/2430
- [ ] <Any other follow up items>

/help
cc: @kubernetes/release-engineering

**Comment by xmudrii** [comment]
All work is done.
/close
