### ISSUE TITLE
Dependency update - Golang 1.17.8 /1.16.15

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2450]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2425

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/RP1hfrBYVuk/m/I7ouYouLAAAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1646381267641489

### Work items for `gox.y.z`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2451

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3479

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2451

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3480

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2451

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3481

#### After kube-cross image promotion

- [ ] ~kubernetes/kubernetes update (`master`)~: the main branch is using go 1.18, so we will skip this

  Ensure the following have been updated within the PR:

  - [ ] ~kube-cross image~
  - [ ] ~go-runner image~
  - [ ] ~publishing bot rules~
  - [ ] ~test image~

#### After kubernetes/kubernetes (1.23) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2463

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2463

### Cherry picks

- [x] Kubernetes 1.23: https://github.com/kubernetes/kubernetes/pull/108559
- [x] Kubernetes 1.22: https://github.com/kubernetes/kubernetes/pull/108564
- [x] Kubernetes 1.21: https://github.com/kubernetes/kubernetes/pull/108565

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/108685

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2463

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2463

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/25612

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

/assign
cc: @kubernetes/release-engineering

**Comment by cpanato** [comment]
all work is done
/close
