### ISSUE TITLE
Dependency update - Golang 1.18.1/1.17.9

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2499]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2307 / https://github.com/kubernetes/release/issues/2450

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/oecdBNLOml8/m/Qpa5hGjrBwAJ?utm_medium=email&utm_source=footer

SIG Release Slack thread: 

### Work items for `gox.y.z`

- [ ] `kube-cross` image update: 

  
  - [ ] image promotion: 

- [ ] `go-runner` image update: 

  
  - [ ] image promotion: 

- [ ] `releng-ci` image update: 

  
  - [ ] image promotion: 

#### After kube-cross image promotion

- [ ] kubernetes/kubernetes update (`master`): 

  Ensure the following have been updated within the PR:

  - [ ] kube-cross image
  - [ ] go-runner image
  - [ ] publishing bot rules
  - [ ] test image

#### After kubernetes/kubernetes (master) has been updated

- [ ] `k8s-cloud-builder` image update: 

- [ ] `k8s-ci-builder` image variants update: 

### Cherry picks

- [ ] Kubernetes x.y-1: 
- [ ] Kubernetes x.y-2: 
- [ ] Kubernetes x.y-3: 

- [ ] publishing bot rule updates for active Golang versions: 

#### After kubernetes/kubernetes (release branches) has been updated

- [ ] `k8s-cloud-builder` image update: 

- [ ] `k8s-ci-builder` image variants update: 

- [ ] `kubekins`/`krte` image variants update: 

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

/assign
cc: @kubernetes/release-engineering

**Comment by cpanato** [comment]
all work is complete
/close
