### ISSUE TITLE
Dependency update - Golang 1.18.2/1.17.10

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2520]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2499

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/Y5qrqw_lWdU/m/SaBMIU9JAQAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1652254961371939

### Work items for `go1.18/go1.17`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2521

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3731

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2521

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3732

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2521

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3733

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/110043

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image

#### After kubernetes/kubernetes (master/release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2526

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2526

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/26326

### Cherry picks

- [x] Kubernetes 1.24 go1.18: https://github.com/kubernetes/kubernetes/pull/110044
- [x] Kubernetes 1.23 go1.17: https://github.com/kubernetes/kubernetes/pull/110045

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/110050

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

/assign
cc: @kubernetes/release-engineering

**Comment by cpanato** [comment]
all work is done
/close
