### ISSUE TITLE
Dependency update - Golang 1.18.3/1.17.11

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2541]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2520

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/TzIC9-t8Ytg

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1654118736031189

### Work items for `go1.18/go1.17`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2542

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3802

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2542

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3803

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2542

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3804

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/110421

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2547

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2547

### Cherry picks

- [x] Kubernetes 1.24: https://github.com/kubernetes/kubernetes/pull/110422 
- [x] Kubernetes 1.23: https://github.com/kubernetes/kubernetes/pull/110423

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/110427

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2547

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2547

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/26513

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements

/assign
cc: @kubernetes/release-engineering

**Comment by cpanato** [comment]
all work is done
/close
