### ISSUE TITLE
Dependency update - Golang 1.19.0

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2575]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2307

Golang mailing list announcement:

- go1.19beta1: https://groups.google.com/g/golang-announce/c/SNruPJUSFz0/m/8QKkkMpJAAAJ
- go1.19rc1: https://groups.google.com/g/golang-announce/c/Lu8ODY19HhA/m/u8N2CpbjAgAJ
- go1.19rc2: https://groups.google.com/g/golang-announce/c/czoG5UpT0EU
- go1.19: https://groups.google.com/g/golang-announce/c/hwjGDuSVZJo

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1655737178508469

### Work items for `go1.19beta1`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2576

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3892

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2576

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3893

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2576

  
  - [x] image promotion: not promoting this image

### Work items for `go1.19rc1`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2601
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3946

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2601
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3947

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2601
  - [x] image promotion: not promoting this image

### Work items for `go1.19rc2`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2610
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3990

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2610
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/3990

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2610
  - [x] image promotion: not promoting this image

### Work items for `go1.19`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2628
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4047

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2628
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4047

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2628
  - [x] image promotion: not promoting this image

#### After kube-cross image promotion

- [ ] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/111679

  Ensure the following have been updated within the PR:

  - [x] kube-cross image https://github.com/kubernetes/kubernetes/pull/111679/commits/79df9e66f30067b885ddbf1f883f741ada51d090
  - [x] go-runner image https://github.com/kubernetes/kubernetes/pull/111679/commits/7324b781fe38f6d94d31f48f59ae29965d548477
  - [x] publishing bot rules https://github.com/kubernetes/kubernetes/pull/111679/commits/2be8ac828eade42e906aa0ce2e4ce5781086ada9
  - [x] test image https://github.com/kubernetes/kubernetes/pull/111679/commits/5d2de1895676b803bbe7d1975a980d97cb115d7c

#### After kubernetes/kubernetes (master) has been updated

- [ ] `k8s-cloud-builder` image update: 

- [ ] `k8s-ci-builder` image variants update: 

### Cherry picks

- [ ] Kubernetes x.y-1: 
- [ ] Kubernetes x.y-2: 
- [ ] Kubernetes x.y-3: 

- [ ] publishing bot rule updates for active Golang versions: 

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2631

- [ ] `k8s-ci-builder` image variants update: 

- [ ] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/26654

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

/assign
cc: @kubernetes/release-engineering

**Comment by pacoxu** [comment]
golang 1.19 was GAed.
https://github.com/kubernetes/kubernetes/issues/111297 is pending on this.

**Comment by cpanato** [comment]
all done here
/close
