### ISSUE TITLE
Dependency update - Golang 1.18.4/1.17.12

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2620]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2541

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/nqrv9fbR0zE

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1658907492108609

### Work items for `gox.y.z`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2621

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4019

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2621

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4020

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2621

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4022

#### After kube-cross image promotion

- [ ] kubernetes/kubernetes update (`master`): not doing the main branch becasue that will get go1.19 soon. check the slack thread above

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image

#### After kubernetes/kubernetes (master) has been updated

- [ ] `k8s-cloud-builder` image update: 

- [ ] `k8s-ci-builder` image variants update: 

### Cherry picks

- [x] Kubernetes 1.24: https://github.com/kubernetes/kubernetes/pull/111464
- [x] Kubernetes 1.23: https://github.com/kubernetes/kubernetes/pull/111465

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/111500

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2429

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2429

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/26952

### Follow-up items

- [x] Ensure the Golang issue template is updated with any new requirements

/assign
cc: @kubernetes/release-engineering

**Comment by cpanato** [comment]
all work is done
/close
