### ISSUE TITLE
Dependency update - Golang 1.18.5/1.17.13

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2625]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2620 

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/YqYYG87xB10/m/NzQjeXshBAAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1659371038194929

### Work items for `gox.y.z`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2626

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4041

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2626

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4042

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2626

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4043

#### After kube-cross image promotion

- [ ] kubernetes/kubernetes update (`master`): **not doing the main branch becasue that will get go1.19 soon. check the slack thread above**

  Ensure the following have been updated within the PR:

  - [ ] kube-cross image
  - [ ] go-runner image
  - [ ] publishing bot rules
  - [ ] test image

#### After kubernetes/kubernetes (master) has been updated

- [ ] `k8s-cloud-builder` image update: 

- [ ] `k8s-ci-builder` image variants update: 

### Cherry picks

- [x] Kubernetes 1.24: https://github.com/kubernetes/kubernetes/pull/111639
- [x] Kubernetes 1.23: https://github.com/kubernetes/kubernetes/pull/111640

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/111685

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2630

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2630

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/27024

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

/assign
cc: @kubernetes/release-engineering

**Comment by cpanato** [comment]
all work is done for this 🎉 
/close
