### ISSUE TITLE
Dependency update - Golang 1.19.1/1.18.6

### ISSUE THREAD

**Issue by palnabarun** [kubernetes/release#2658]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2625

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/x49AQzIVX-s

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1662484605170979

### Work items
- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2659
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4189
- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2659
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4190
- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2659
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4191

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/112287
  Ensure the following have been updated within the PR: 
  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2660
- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2660

### Cherry picks

- [x] Kubernetes 1.25: https://github.com/kubernetes/kubernetes/pull/112320
- [x] Kubernetes 1.24: https://github.com/kubernetes/kubernetes/pull/112322

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/112329

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2660
- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2660
- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/27423

### Follow-up items

- [x] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

/assign
cc: @kubernetes/release-engineering

**Comment by palnabarun** [comment]
TODO: Update the AIs above.

**Comment by palnabarun** [comment]
All items done!

/close
