### ISSUE TITLE
Dependency update - Golang 1.19.2/1.18.7

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#2694]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2658

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/xtuG5faxtaU/m/jEhlI_5WBgAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1664911085960369

### Work items for `go1.19.2` and `go1.18.7`

- [x] `kube-cross` image update: #2696

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4312

- [x] `go-runner` image update: #2696

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4313

- [x] `releng-ci` image update: #2696

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4314

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/112900

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2699

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2699

### Cherry picks

- [x] Kubernetes 1.25: https://github.com/kubernetes/kubernetes/pull/112902 
- [x] Kubernetes 1.24: https://github.com/kubernetes/kubernetes/pull/112903

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/112904

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2699

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2699

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/27712

### Follow-up items

- [x] Ensure the Golang issue template is updated with any new requirements: https://github.com/kubernetes/release/pull/2701

/assign
cc: @kubernetes/release-engineering

**Comment by xmudrii** [comment]
We’re done with updates.
