### ISSUE TITLE
k8s.gcr.io VDF (Vanity Domain Flip): Move official container images to K8s Infra

### ISSUE THREAD

**Issue by jbeda** [kubernetes/release#270]
### Google Infra --> K8s Infra tasks (ordered by priority):

- [x] Ensure that `k8s-artifacts-prod` GCR is a superset of google-containers (aka backfiling; this has already been [done](https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io/manifests/DO-NOT-MODIFY-legacy-backfill) and is easy to check before VDF happens)
- [x] Fix auditor's ability to handle child images in fat manifests ([issue](https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/191))
- [x] Optimize backup mechanism ([issue](https://github.com/kubernetes/k8s.io/issues/666))
- [x] Add CLI command to make editing the promoter manifests easier ([issue](https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/190))
- [ ] Auditor alerts --> `<somewhere>`

### Release Engineering

- [x] (https://github.com/kubernetes/k8s.io/pull/624) Create `k8s-staging-kubernetes` GCP project (prod staging project)
- [x] (https://github.com/kubernetes/k8s.io/pull/623) Backfill prod k8s.gcr.io images
- [x] Figure out image promotion for staging
  - [x] (https://github.com/kubernetes/k8s.io/pull/645) Configure `k8s-staging-kubernetes` promoter-manifest to point to test prod namespace
  - [x] (https://github.com/kubernetes/k8s.io/pull/673, https://github.com/kubernetes/k8s.io/pull/675) Grant `kubernetes-release-test` GCB write on `k8s-staging-kubernetes` GCR
  - [x] (https://github.com/kubernetes/release/pull/1199) Publish container images on K8s Infra (`k8s-staging-kubernetes`)
  - [x] Add CLI command to dump and merge an image manifest for promotion - https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/190

---
Original note from @jbeda:
> We should not be using a Google only repo for official k8s builds.

**Comment by ixdy** [comment]
Yep, this is something that @timstclair and I are looking into.

**Comment by timstclair** [comment]
We're expecting to have a proposal out in the next week or two that will address this.

**Comment by zmerlynn** [comment]
Please include me. We have internal infrastructure that handles the replication of `google-containers` to non-US regions.

**Comment by luxas** [comment]
Please include me as well, I have been thinking about this for some time as well, but haven't just had the time to focus fully on trying to make a change here (not that I have the permissions to do so either but :smile:)

**Comment by david-mcmahon** [comment]
cc @javier-b-perez

**Comment by luxas** [comment]
Progress: https://github.com/kubernetes/kubernetes/pull/54174

/remove-lifecycle stale

cc @thockin @ixdy 

What are the next steps here?
To start moving over images to a specific Kubernetes suborg gradually and/or updating refs in all other repos as well?

**Comment by listx** [comment]
I really hope this will happen in the coming months. Check out this [issue](https://github.com/kubernetes/k8s.io/issues/157) for high-level updates, but also updates to the `manifest.yaml` files [here](https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io), as this is the first batch of staging registries that will be using the new non-Googler promotion process.

Or, please attend the [wg-k8s-infra meetings](https://github.com/kubernetes/community/tree/master/wg-k8s-infra) where updates to this work is currently on the agenda.

**Comment by justaugustus** [comment]
It's happening (soon-ish)!!
ref: https://groups.google.com/d/topic/kubernetes-dev/MkXnkTSJ_vs/discussion / https://twitter.com/stephenaugustus/status/1234990491323600896?s=20

/unassign @timothysc @tallclair 
/assign @listx @thockin

**Comment by thockin** [comment]
Huge thanks to @listx for doing most of the heavy lifting on this.  We're not just changing it, we're making the whole mechanism SIGNIFICANTLY more resilient and secure at the same time.  I have moved the goalposts on him at least thrice, so .... sorry about that :)

**Comment by listx** [comment]
Three items remain, ordered by priority:

- ensure that k8s-artifacts-prod GCR is a superset of google-containers (aka backfilling; this has already been [done](https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io/manifests/DO-NOT-MODIFY-legacy-backfill) and is easy to check before VDF happens)
- fix auditor's ability to handle child images in fat manifests ([issue](https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/191))
- optimize backup mechanism ([issue](https://github.com/kubernetes/k8s.io/issues/666))
- add CLI command to make editing the promoter manifests easier ([issue](https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/190))

**Comment by thockin** [comment]
Auditor alerts -> <somewhere>

**Comment by jackfrancis** [comment]
@justaugustus May I offer to add back-compat validation once the cutover occurs? Lots of folks in the wild, as has been mentioned by other folks, will continue to have dependencies on the k8s.gcr.io URLs. Sounds like there's a plan to protect those URLs being redirects + read-only access indefinitely; lemme know if I can help prove that out!

@ritazh FYI

**Comment by BenTheElder** [comment]
ER @jackfrancis the `k8s.gcr.io` urls are going nowhere, but they will be in front of a new backing registry. 

`k8s.gcr.io` is currently a regionalized alias to ~`gcr.io/google_containers` which is in a google.com owned GCP project, but k8s.gcr.io be moving to be an alias for a community owned bucket.

Then plan is to ensure that all existing images in the current backing bucket are mirrored into the new bucket as part of the switch.

The old bucket is also not really going away, we're just going to stop using this to host the community images.

**Comment by jackfrancis** [comment]
@BenTheElder thanks for implementation detail details! ACK that this isn't something to worry about from a boring, consumption of k8s.gcr.io standpoint. :)

**Comment by justaugustus** [comment]
Thanks for providing details, @BenTheElder!

**Comment by listx** [comment]
I am prioritizing the backup optimization issue because it needs some form of design. Design doc here: https://github.com/kubernetes/k8s.io/issues/666#issuecomment-601481514

**Comment by justaugustus** [comment]
@listx -- Would you mind providing an update on your side as we're nearing the date?

**Comment by listx** [comment]
I'm manually performing the backups for now to make the automated jobs not time-out and cause a quota exceeded error. The backup optimization implementation has hit a snag with Workload Identity here https://github.com/kubernetes/k8s.io/pull/677, but that should be sorted out by EOD tomorrow.

The auditor has had fixes to child manifest detection and this has been rolled out earlier today.

There is an internal Google change that will start rolling out on Wednesday (April 1) morning for the flip itself. As k8s-artifacts-prod has been a superset of google-containers for a while now, the transition should be seamless. (However, I will perform another backfill if necessary tomorrow).

The backup stuff is in a bit of a pinch but I don't think it will take longer than tomorrow to sort out (in time for the flip on Wed morning).

**Comment by justaugustus** [comment]
@listx -- Thanks for the update! I think we're fine for day 1 as long as the backfill is set (which it is) and we've got a go-forward plan for the backups (which we do).

On my end, I've successfully tested the Releng changes [here](https://github.com/kubernetes/release/pull/1199). I'm going to do a few spot-checks just in case, but we should be all good to go! :)

**Comment by listx** [comment]
The flip is in progress. Charts and updates haven been posted here: https://groups.google.com/d/msg/kubernetes-sig-release/ew-k9PEBckQ/mSa7KGeUCAAJ

**Comment by listx** [comment]
Forgot to update this thread, but TL;DR: the flip has been rolled back due to an unforeseen issue. Details here: https://groups.google.com/d/msg/kubernetes-sig-release/ew-k9PEBckQ/SZC2KeFYAwAJ

We will attempt the flip again in the coming weeks; I will update this thread again once we decide on the date.

**Comment by justaugustus** [comment]
Last I chatted w/ @listx ETA is in a few weeks.
They're still working on some stuff on the Google side.

**Comment by thockin** [comment]
I gave a quick update at the WG meeting.  TL;DR is that over time, bad
assumptions grow deep roots.  We're disentangling the roots now, but it
reaches across several teams, and we've already caused one problem with
this, so "once bitten, twice shy" is in full effect.  We believe we're
close.  O(weeks) seems right.

**Comment by listx** [comment]
I vote to close this as [VDF was completed on July 24, 2020](https://groups.google.com/g/kubernetes-sig-release/c/lFmJZKwIxyI/m/ytVrkTYNAQAJ).
