### ISSUE TITLE
Dependency update - Golang 1.19.3/1.18.8

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#2726]
**Releases are scheduled for November 1st.**

### Tracking info

Link to any previous tracking issue: #2694

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/dRtDK7WS78g/m/7v0ebkTJBAAJ

SIG Release Slack thread: 

### Work items

- [ ] `kube-cross` image update: 

  
  - [ ] image promotion: 

- [ ] `go-runner` image update: 

  
  - [ ] image promotion: 

- [ ] `releng-ci` image update: 

  
  - [ ] image promotion: 

#### After kube-cross image promotion

- [ ] kubernetes/kubernetes update (`master`): 

  Ensure the following have been updated within the PR:

  - [ ] kube-cross image
  - [ ] go-runner image
  - [ ] publishing bot rules
  - [ ] test image

#### After kubernetes/kubernetes (master) has been updated

- [ ] `k8s-cloud-builder` image update: 

- [ ] `k8s-ci-builder` image variants update: 

### Cherry picks

- [ ] Kubernetes x.y-1: 
- [ ] Kubernetes x.y-2: 
- [ ] Kubernetes x.y-3: 

- [ ] publishing bot rule updates for active Golang versions: 

#### After kubernetes/kubernetes (release branches) has been updated

- [ ] `k8s-cloud-builder` image update: 

- [ ] `k8s-ci-builder` image variants update: 

- [ ] `kubekins`/`krte` image variants update: 

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

cc: @kubernetes/release-engineering

**Comment by cpanato** [comment]
thanks @xmudrii for leading this, let me know if you need help
