### ISSUE TITLE
Dependency update - Golang 1.19.4/1.18.9

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#2788]
**Releases are scheduled for Tuesday, December 6.**

### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2726

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/v2KvT18_yCg/m/WKTrlMftAAAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1669846712157929

### Work items

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2794

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4523

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2794

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4524

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2794

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4525

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/114284

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2795

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2795

### Cherry picks

- [x] Kubernetes 1.26: will be fast-forwarded (https://testgrid.k8s.io/sig-release-releng-blocking#git-repo-kubernetes-fast-forward)
- [x] Kubernetes 1.25: https://github.com/kubernetes/kubernetes/pull/114286
- [x] Kubernetes 1.24: https://github.com/kubernetes/kubernetes/pull/114287

- [ ] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/114288

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2795

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2795

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/28177

### Follow-up items
- [x] Ensure the Golang issue template is updated with any new requirements

/assign
cc: @kubernetes/release-engineering
