### ISSUE TITLE
Dependency update - Golang 1.20.0

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2815]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2575

Golang mailing list announcement:

- go1.20rc1: https://groups.google.com/g/golang-announce/c/iqUo0Spdl9I/m/r6EJ6wR5BQAJ

SIG Release Slack thread: 

### Work items for `Go1.20rc1`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2816

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4550

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2816

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4551

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2816

  
  - [x] image promotion: not promoting this image

### Work items for `Go1.20rc2`

announcement: https://groups.google.com/g/golang-announce/c/muM4ByrIMbM/m/U14tSKsbBAAJ

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2846

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4601

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2846

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4602

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2846

  
  - [x] image promotion: not promoting this image

### Work items for `Go1.20rc3`

announcement: https://groups.google.com/g/golang-announce/c/7SPnPbP2DTU/m/4tLT-Rg3AwAJ

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2857

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4639

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2857

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4638

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2857

  
  - [x] image promotion: not promoting this image
  
### Work items for `Go1.20`

announcement: https://groups.google.com/g/golang-announce/c/QMK8IQALDvA/m/JbovhzpOAAAJ

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2887

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4722

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2887

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4723

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2887

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4724

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/114502

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2895

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2895

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/28651

### Follow-up items

- [x] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

/assign
cc: @kubernetes/release-engineering

**Comment by liggitt** [comment]
Tracking PRs merges related to go1.20 that we would need to pick to release branches as part of an eventual update to go1.20:
- https://github.com/kubernetes/kubernetes/pull/114078
- fix for https://github.com/kubernetes/kubernetes/issues/114145
- https://github.com/kubernetes/kubernetes/pull/114766

**Comment by xmudrii** [comment]
@cpanato @liggitt Are we good to close this issue? If not, what are remaining tasks?

**Comment by liggitt** [comment]
I'm still tracking taking 1.20 back to release-1.{24,25,26} in https://github.com/kubernetes/release/issues/2815#issuecomment-1373891562

**Comment by liggitt** [comment]
go 1.20 has been out for 3 months now, there are no open golang issues tracking backports of regression fixes to 1.20, and we're approaching 1 month after 1.27.0 release, so it's probably time to get the [last prereq PRs](https://github.com/kubernetes/release/issues/2815#issuecomment-1373891562) merged to release-1.{24,25,26} to prep for bumping those branches to go1.20

**Comment by liggitt** [comment]
Ok, the 1.24-1.26 temporary PRs bumping just .go-version passed all tests and passed integration and unit tests on the original go versions for those branches. 

I think we're ready for the real bumps with kube-cross updates, etc, then we can close out this issue 🎉 

Can release management folks pick up the image/version bump PRs?

**Comment by cpanato** [comment]
I will take it

/assign

**Comment by liggitt** [comment]
did 1.24-1.26 ever get updated to go1.20?

**Comment by xmudrii** [comment]
As per https://github.com/kubernetes/release/blob/27700ffed3109700889f40b7bc8d690d90ea8dc5/images/k8s-cloud-builder/variants.yaml#L1, no.

**Comment by liggitt** [comment]
any blockers? getting 1.24-1.26 onto go1.20 before go1.19 hits EOL is important

**Comment by cpanato** [comment]
no blockers, if this is ready to be upgraded i will start working on that, will wait your green light @liggitt

**Comment by cpanato** [comment]
- [ ] go images: https://github.com/kubernetes/release/pull/3144 got 1.26/1.25/1.24

**Comment by cpanato** [comment]
closing branches are in 1.20 now 🎉 

/close
