### ISSUE TITLE
Dependency update - Golang 1.19.4 on release-1.23 and release-1.24

### ISSUE THREAD

**Issue by liggitt** [kubernetes/release#2822]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2788

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/L_3rmdT0BMU

SIG Release Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1671026815368429

### Work items

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2825
 
  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4552

- [x] `go-runner` image update: not needed

  
  - [x] image promotion: not needed

- [x] `releng-ci` image update: not needed

  
  - [x] image promotion: not needed

#### After kube-cross image promotion

- [x] Kubernetes 1.24: https://github.com/kubernetes/kubernetes/pull/113956 
- [x] Kubernetes 1.23: https://github.com/kubernetes/kubernetes/pull/113983  

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image

### Cherry picks

- publishing bot rule updates for active Golang versions: 
  - [x] 1.23: https://github.com/kubernetes/kubernetes/pull/114648
  - [x] 1.24: https://github.com/kubernetes/kubernetes/pull/114645

#### After kubernetes/kubernetes (release branches) has been updated

1.24:

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2830

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2830

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/28289

1.23:

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2832

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2832

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/28293

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

/assign
cc: @kubernetes/release-engineering

**Comment by liggitt** [comment]
/unassign
/cc @xmudrii @cpanato 
xref https://github.com/kubernetes/release/pull/2802#issuecomment-1351328068

**Comment by liggitt** [comment]
one difference between this and normal go image bumps is that we probably want to *add* the 1.23/1.24+go1.19 images alongside the existing images (instead of replacing 1.23+go1.17 and 1.24+go1.18) until we solidify the k/k PRs and CI

**Comment by liggitt** [comment]
the k/k 1.23 and 1.24 PRs are updated, do we have canary unit/integration/dependency CI jobs on those branches we can bump go versions on to make sure CI is happy on go1.19 before updating the main CI jobs' go version?

**Comment by liggitt** [comment]
k/k branches, publishing bot, test-infra, and release builder images are updated

marking this as closed, thanks for all the coordination @cpanato @xmudrii @dims

/close
