### ISSUE TITLE
Dependency update - Golang 1.19.5/1.18.10

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2851]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2788

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/wrmRT7JlevE/m/YDMZrEc0AwAJ

SIG Release Slack thread: 

### Work items

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2853

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4622

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2853

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4620

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2853

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4621

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/115010

  Ensure the following have been updated within the PR: 

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image
  - [x] `.go-version` file

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2856

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2856

### Cherry picks

- [x] Kubernetes 1.23: https://github.com/kubernetes/kubernetes/pull/115011
- [x] Kubernetes 1.24: https://github.com/kubernetes/kubernetes/pull/115012
- [x] Kubernetes 1.25: https://github.com/kubernetes/kubernetes/pull/115013
- [x] Kubernetes 1.26: https://github.com/kubernetes/kubernetes/pull/115014

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/115029

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2856

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2856

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/28411

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

/assign
cc: @kubernetes/release-engineering

**Comment by liggitt** [comment]
(as a side note, I think we only need 1.19.5 images, since all release branches are on go1.19 now)

**Comment by cpanato** [comment]
i will cleanup the 1.18 references later

**Comment by cpanato** [comment]
all work is done, closing

/close
