### ISSUE TITLE
Dependency update - Golang 1.20.1/1.19.6

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2909]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2851 / https://github.com/kubernetes/release/issues/2815

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/2zqu2BOnpP8/m/3ECQJP56AwAJ

SIG Release Slack thread: 

### Work items

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2914

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4785

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2914

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4783

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2914

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4784

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/115828

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image
  - [x] `.go-version` file

#### After kubernetes/kubernetes (master) has been updated

- [ ] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2921

- [ ] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2921

### Cherry picks

- [x] Kubernetes 1.23: https://github.com/kubernetes/kubernetes/pull/115830
- [x] Kubernetes 1.24: https://github.com/kubernetes/kubernetes/pull/115831
- [x] Kubernetes 1.25: https://github.com/kubernetes/kubernetes/pull/115832
- [x] Kubernetes 1.26: https://github.com/kubernetes/kubernetes/pull/115833

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/115855

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2921

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2921

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/28781

### Follow-up items

- [x] Ensure the Golang issue template is updated with any new requirements

/assign
cc: @kubernetes/release-engineering

**Comment by liggitt** [comment]
We also need to update to v0.7.0 of https://github.com/golang/net/releases/tag/v0.7.0 to pick up the CVE-2022-41723 fix

**Comment by cpanato** [comment]
all work is done for now
/close

**Comment by jingyuanliang** [comment]
As a note, these two images contain gorunner which will be affected by a Golang stdlib CVE / version bump.

**Comment by cpanato** [comment]
@cici37 @jingyuanliang let me take a look, we have too many images 😅

**Comment by cpanato** [comment]
@cici37 @jingyuanliang yes makes sense, can you please open a PR to update the template?
