### ISSUE TITLE
Dependency update - Golang 1.20.2/1.19.7

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#2948]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2909

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/3-TpUx48iQY/m/Ujnw4fFHAQAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1678208751242099

### Work items

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/2949

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4895

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/2949

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4896

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/2949

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4897

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/116404

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image
  - [x] `.go-version` file

#### After go-runner image promotion

- [x] `debian-iptables` image update: https://github.com/kubernetes/release/pull/2954

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4917

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/2954

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/4918

#### After distroless-iptables image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/116509

  Ensure the following have been updated within the PR:

  - [x] distroless-iptables image
  - [x] test image

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2955

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2955

### Cherry picks

- [x] Kubernetes 1.23: not doing because it is EOL 
- [x] Kubernetes 1.24: https://github.com/kubernetes/kubernetes/pull/116405
- [x] Kubernetes 1.25: https://github.com/kubernetes/kubernetes/pull/116406
- [x] Kubernetes 1.26: https://github.com/kubernetes/kubernetes/pull/116407

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/116456

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/2955

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/2955

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/28971

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

/assign
cc: @kubernetes/release-engineering

**Comment by cpanato** [comment]
all done

/close
