### ISSUE TITLE
Fix unsigned patch releases

### ISSUE THREAD

**Issue by puerco** [kubernetes/release#2962]
While cutting the February patch releases, the image promoter got rate limited by Fulcio, the sigstore certificate authority (see [this long thread in slack](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1677093689737729) for more context). This caused the signatures in the published images to be in an inconsistent state: some images are signed, some not, and some don't have their signatures replicated.

In order to fix the problem we need to check the signatures of images, ensure they are signed with the expected identity, and that they are correctly replicated. Then, based on that there are two actions to be taken:

1. Sign and replicate those missing signatures
2. Replicate signatures of any partially signed images

After manually fixing these, we can move the promoter subcommand to audit the signatures in the future.

### Justification

The signatures on our images are the stamp of approval to show that the community approved them to be published to the production registries. Any signed image can be traced back to a PR in a manifest where the change was signed off by the relevant community members. We can always sign them after publishing by ensuring we are signing on the correct digests based on the manifest data.

### Action Plan
- [x] Manually map out which images were affected [slack ref](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1677603166388709?thread_ts=1677597577.288549&cid=CJH2GBF7Y)
- [x] Add a command to the image promoter to find unsigned images, it should support date ranges and `--dry-run` to check what it would do<br> https://github.com/kubernetes-sigs/promo-tools/pull/745<br> https://github.com/kubernetes-sigs/promo-tools/pull/767
- [x] Expose the concurrency limits to control them from the promoter's job configuration<br>https://github.com/kubernetes-sigs/promo-tools/pull/770
- [x] Rate limit copy calls in the promoter to stay under the AR quotas<br>https://github.com/kubernetes-sigs/promo-tools/pull/771
- https://github.com/kubernetes-sigs/promo-tools/issues/752
- [ ] Create a one-time run to ensure running within prow has the correct view of things
- [ ] Do a test run with one of the images
- [ ] Run it on the rest images
- [ ] Update the promoter code to verify any unsigned images against the manifests to ensure we sign allowed artifacts
- [ ] Modify the job to constantly audit and verify the latest promoted images

/cc @cpanato @kubernetes/release-managers

**Comment by puerco** [comment]
The scope of this issue is now expanded to fix the March patches which got rate limited when calling the registry. This is a new problem and we now have to maneuver around the AR registry limits  [[slack ref](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1678895816204009?thread_ts=1678861049.737169&cid=CJH2GBF7Y)].

**Comment by anshikavashistha** [comment]
@puerco This project seems interesting to me. I really want to work on this project .Is there any prerequisite task that needs to be done ?
Please share the link of community channel or any slack channel.

**Comment by saschagrunert** [comment]
Closing as the signing infrastructure has changed significantly since this was filed.
