### ISSUE TITLE
Dependency update - Golang 1.20.3/1.19.8

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#2991]
### Tracking info

Link to any previous tracking issue: #2948

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/71Wg3N0IZk0/m/xchF2bEZAgAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1680462499542979

### Work items

- [x] `kube-cross` image update: #3000

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5088

- [x] `go-runner` image update: #3000

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5089

- [x] `releng-ci` image update: #3000

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5090, https://github.com/kubernetes/k8s.io/pull/5091

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/117125

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image
  - [x] `.go-version` file

#### After go-runner image promotion

- [x] `debian-iptables` image update: https://github.com/kubernetes/release/pull/3001

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5095

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/3001

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5094

#### After distroless-iptables image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/117126

  Ensure the following have been updated within the PR:

  - [x] distroless-iptables image
  - [x] test image

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/3004

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/3004

### Cherry picks

- [x] Kubernetes 1.24: https://github.com/kubernetes/kubernetes/pull/117132
- [x] Kubernetes 1.25: https://github.com/kubernetes/kubernetes/pull/117131
- [x] Kubernetes 1.26: https://github.com/kubernetes/kubernetes/pull/117133
- [x] Kubernetes 1.27: fast-forward (https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-fast-forward/1643883672211820544)

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/117134

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/3006

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/3006

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/29239

### Follow-up items

- [x] Ensure the Golang issue template is updated with any new requirements

/assign
cc: @kubernetes/release-engineering

**Comment by xmudrii** [comment]
Go is updated on master and all supported release branches.
/close
