### ISSUE TITLE
Dependency update - Golang 1.20.4/1.19.9

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#3025]
### Tracking info

Link to any previous tracking issue: #2991

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/vFRFE07dbB8/m/vM-aS7KGAAAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1682609128795289

### Work items

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/3029

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5202

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/3029

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5203

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/3029

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5204

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/117744

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image
  - [x] `.go-version` file

#### After go-runner image promotion

- [x] `debian-iptables` image update: https://github.com/kubernetes/release/pull/3031

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5206

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/3031

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5206

#### After distroless-iptables image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/117746

  Ensure the following have been updated within the PR:

  - [x] distroless-iptables image
  - [x] test image

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/3032

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/3032

### Cherry picks

- [x] Kubernetes 1.27: https://github.com/kubernetes/kubernetes/pull/117773
- [x] Kubernetes 1.26: https://github.com/kubernetes/kubernetes/pull/117774
- [x] Kubernetes 1.25: https://github.com/kubernetes/kubernetes/pull/117775
- [x] Kubernetes 1.24: https://github.com/kubernetes/kubernetes/pull/117776

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/117778

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/3034

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/3034

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/29420

### Follow-up items

- [x] Ensure the Golang issue template is updated with any new requirements

/assign
cc: @kubernetes/release-engineering

**Comment by rayandas** [comment]
Hi @xmudrii is there any way I can contribute here? I went through an [old issue](https://github.com/kubernetes/release/issues/2991) (and related PRs) similar to this as well to understand how it’s done.

**Comment by xmudrii** [comment]
@rayandas Generally, Go updates are taken care of Release Managers, but there are some tasks that can be done together. If you want, take a look at #3000 and try to create a similar PR for Go 1.20.4 / 1.19.9. You can already do that, and we'll run tests and try to merge the PR as soon as releases are available.

**Comment by rayandas** [comment]
Surely @xmudrii I will raise a PR for that today. Thanks.
