### ISSUE TITLE
Dependency update - Golang 1.21.0

### ISSUE THREAD

**Issue by liggitt** [kubernetes/release#3076]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/2815

Golang mailing list announcement: 

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1687945498281579

### Work items for `Go1.21rc2`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/3132

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5492

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/3132

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5493

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/3132

  
  - [x] image promotion: not promoting this image

### Work items for `Go1.21rc3`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/3155

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5587

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/3155

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5588

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/3155

  
  - [x] image promotion: not promoting this image

### Work items for `Go1.21`

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/3212

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5740

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/3212

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5741

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/3212

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5742

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/118996

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image
  - [x] `.go-version` file

#### After go-runner image promotion

- [ ] `debian-iptables` image update: 

  
  - [ ] image promotion: 

- [ ] `distroless-iptables` image update: 

  
  - [ ] image promotion: 

#### After distroless-iptables image promotion

- [ ] kubernetes/kubernetes update (`master`): 

  Ensure the following have been updated within the PR:

  - [ ] distroless-iptables image
  - [ ] test image

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/3250

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/3251

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/30631

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

/assign
cc: @kubernetes/release-engineering

**Comment by liggitt** [comment]
Placeholder for tracking PRs to master branch required for 1.21, for later cherry pick to release branches

- https://github.com/kubernetes/kubernetes/pull/118150

**Comment by rsc** [comment]
Also the PR for https://github.com/kubernetes/kubernetes/issues/118153 (don't think there is one yet but I pasted the patch in the report).

**Comment by neolit123** [comment]
@cpanato please help approve the open (green) cherry picks mentioned here:
https://github.com/kubernetes/release/issues/3076#issuecomment-1556053267

**Comment by neolit123** [comment]
> 1.27: https://github.com/kubernetes/kubernetes/pull/118169

was repaced with https://github.com/kubernetes/kubernetes/pull/119086

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/120279 (shim existing go toolchain management to GOTOOLCHAIN)

**Comment by dims** [comment]
cc @danbudris @zafs23

**Comment by liggitt** [comment]
changes lgtm, prereqs are met, I think we can go ahead and do the release branch bumps for real

**Comment by cpanato** [comment]
Cool, i will start the process

**Comment by humblec** [comment]
@cpanato will we complete the bump to` 1.21.7` in k8s release <= v1.28 and make it ready for Feb patches?

**Comment by cpanato** [comment]
> @cpanato will we complete the bump to` 1.21.7` in k8s release <= v1.28 and make it ready for Feb patches?

this is on going right now :)

**Comment by liggitt** [comment]
updated in https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+%22go+1.21.7%22+is%3Amerged+-base%3Amaster

added links to https://github.com/kubernetes/release/issues/3076#issuecomment-1556053267

/close
as completed
