### ISSUE TITLE
Dependency update - Golang 1.20.5/1.19.10

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/release#3099]
### Tracking info

Link to any previous tracking issue:  https://github.com/kubernetes/release/issues/3025

Golang mailing list announcement:  https://groups.google.com/g/golang-announce/c/1AItFMBjrfw

SIG Release Slack thread:  https://kubernetes.slack.com/archives/CJH2GBF7Y/p1685659171113989

### Work items

- [x] `kube-cross` image update:  https://github.com/kubernetes/release/pull/3105

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5375

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/3105

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5376

- [x] `releng-ci` image update:  https://github.com/kubernetes/release/pull/3105

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5377

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/118507

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image
  - [x] `.go-version` file

#### After go-runner image promotion

- [x] `debian-iptables` image update:  https://github.com/kubernetes/release/pull/3107

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5383

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/3107

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5383
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5384

#### After distroless-iptables image promotion

- [x] kubernetes/kubernetes update (`master`):  https://github.com/kubernetes/kubernetes/pull/118541

  Ensure the following have been updated within the PR:

  - [x] distroless-iptables image
  - [x] test image

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/3108

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/3108

### Cherry picks

- [x] Kubernetes 1.27: https://github.com/kubernetes/kubernetes/pull/118553
- [x] Kubernetes 1.26: https://github.com/kubernetes/kubernetes/pull/118555
- [x] Kubernetes 1.25: https://github.com/kubernetes/kubernetes/pull/118556
- [x] Kubernetes 1.24: https://github.com/kubernetes/kubernetes/pull/118557

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/118629

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update:  https://github.com/kubernetes/release/pull/3116

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/3116

- [x] `kubekins`/`krte` image variants update:  https://github.com/kubernetes/test-infra/pull/29781

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

/assign
cc: @kubernetes/release-engineering

**Comment by cpanato** [comment]
@jeremyrickard I think we can close, or is anything pending?

**Comment by xmudrii** [comment]
@cpanato We should consider updating the base image because the latest Go patch releases are using Debian bookworm. There's a Slack thread about that: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1687267181062359

Let's keep this open until we don't make the final decision and then we can create a new tracking issue for base images update.

**Comment by cpanato** [comment]
sgtm

**Comment by xmudrii** [comment]
We have #3128 to track base image updates. I think we can close this issue.
/close
