### ISSUE TITLE
Switch to debian 12 (bookworm)

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#3128]
Tracking issue to switch to debian 12 for our base images:

- [x] **debian-base**:
  - [x] Image update: https://github.com/kubernetes/release/pull/3127
  - [x] Postsubmit run of `post-release-push-image-debian-base` in k/release:
        https://console.cloud.google.com/cloud-build/builds/29add73b-b9c7-457f-8708-bbc0fdcf63a2
  - [x] Promotion: https://github.com/kubernetes/k8s.io/pull/5506
  - [x] Rollout: https://github.com/kubernetes/kubernetes/pull/119095
- [x] **debian-iptables** (requires debian-base):
  - [x] Image update: https://github.com/kubernetes/release/pull/3136
  - [x] Postsubmit run of `post-release-push-image-debian-iptables`:
        https://console.cloud.google.com/cloud-build/builds/2ddfb03f-2ff1-4e07-8080-71be492709ed?project=960211007710
  - [x] Promotion: https://github.com/kubernetes/k8s.io/pull/5509
  - [x] Rollout: Not required for 1.28, because we now use distroless-iptables,
        see https://github.com/kubernetes/kubernetes/pull/111060)
- [x] **setcap**:
  - [x] Image update: https://github.com/kubernetes/release/pull/3139
  - [x] Postsubmit run of `post-release-push-image-setcap` in k/release:
        https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-setcap/1678773957659987968
  - [x] Promotion: https://github.com/kubernetes/k8s.io/pull/5544
  - [x] Rollout: https://github.com/kubernetes/kubernetes/pull/119247
- [x] **kube-cross**:
  - [x] Image update ([only for v1.28 per mail thread](https://groups.google.com/g/kubernetes-sig-release/c/M-7rt-jvE-8/m/cIC-HS4YBAAJ)): https://github.com/kubernetes/release/pull/3146
  - [x] Postsubmit run of `post-release-push-image-kube-cross` in k/release:
        https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-kube-cross/1679757580605329408
  - [x] Promotion: https://github.com/kubernetes/k8s.io/pull/5574
  - [x] Rollout: will happen in https://github.com/kubernetes/release/issues/3076
- [x] **ci**:
  - [x] Image update: https://github.com/kubernetes/release/pull/3150
  - [x] Postsubmit run of `post-release-push-image-releng-ci` in k/release:
         https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-releng-ci/1679046245521297408
  - [x] Promotion: https://github.com/kubernetes/k8s.io/pull/5546
  - [x] Rollout:
    - [x] https://github.com/kubernetes-sigs/zeitgeist/pull/610
    - [x] https://github.com/kubernetes-sigs/tejolote/pull/132
    - [x] https://github.com/kubernetes-sigs/bom/pull/317
    - [x] https://github.com/kubernetes/test-infra/pull/30068
- [x] **k8s-ci-builder**:
  - [x] Image update: https://github.com/kubernetes/release/pull/3155
  - [x] Postsubmit run of `post-release-push-image-k8s-ci-builder` in k/release:
          https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-k8s-ci-builder/1681720502244085760
  - [x] Promotion: https://github.com/kubernetes/k8s.io/pull/5587
  - [x] Rollout: Comes with https://github.com/kubernetes/release/issues/3076
- [x] **go-runner**:
  - [x] Image update: https://github.com/kubernetes/release/pull/3233
  - [x] Postsubmit run of `post-release-push-image-go-runner` in k/release:
      https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-go-runner/1696484688291434496
  - [x] Promotion: https://github.com/kubernetes/k8s.io/pull/5767
  - [x] Rollout: Comes with https://github.com/kubernetes/release/issues/3076
- [x] **distroless-iptables** (requires go-runner):
  - [x] Image update:
       https://github.com/kubernetes/release/pull/3235
       https://github.com/kubernetes/release/pull/3236
       https://github.com/kubernetes/release/pull/3237
       https://github.com/kubernetes/release/pull/3240
  - [x] Postsubmit run of `post-release-push-image-distroless-iptables` in k/release:
       https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-distroless-iptables/1696855492782985216
       https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-distroless-iptables/1696891736472686592
  - [x] Promotion: https://github.com/kubernetes/k8s.io/pull/5783
  - [x] Rollout: https://github.com/kubernetes/kubernetes/pull/120294

**Comment by saschagrunert** [comment]
Notification mail is out https://groups.google.com/g/kubernetes-sig-release/c/M-7rt-jvE-8/m/zK0lLxu6AgAJ

Setting lazy consens to July 1st before moving on with this topic.

**Comment by saschagrunert** [comment]
Consensus reached, moving forward with debian-base.

**Comment by saschagrunert** [comment]
Mostly done, let's keep this open until we have a `gcr.io/distroless/static-debian12`

**Comment by xmudrii** [comment]
@saschagrunert Do we have an issue to track updating k8s-cloud-builder/k8s-ci-bulider to Debian 12 (bookworm)?

**Comment by saschagrunert** [comment]
> @saschagrunert Do we have an issue to track updating k8s-cloud-builder/k8s-ci-bulider to Debian 12 (bookworm)?

No, the idea was to stay on bullseye as long as possible for compatibility reasons. Like having a policy to always use the lowest available glibc version when building Kubernetes. We may wranna add documentation about this, though.

**Comment by xmudrii** [comment]
> We may wanna add documentation about this, though.

I think that would be very helpful so we can reference it in cases such as https://github.com/kubernetes/release/pull/3430

**Comment by saschagrunert** [comment]
Closing the loop: https://github.com/kubernetes/release/pull/3437
