### ISSUE TITLE
Dependency update - Golang 1.20.6

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#3148]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/3099

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/2q13H6LEEx0/m/sduSepLLBwAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1689095625214579

### Work items

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/3154

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5549

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/3154

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5550

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/3154

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5551

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/119324

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image
  - [x] `.go-version` file

> **Note**
> This update may require an update to go.sum files, for example: https://github.com/kubernetes/kubernetes/pull/118507
> This will require an API Review approval.

#### After go-runner image promotion

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/3156

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5571

#### After distroless-iptables image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/119365

  Ensure the following have been updated within the PR:

  - [x] distroless-iptables image
  - [x] test image

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/3157

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/3157

### Cherry picks

- [x] Kubernetes 1.27: https://github.com/kubernetes/kubernetes/pull/119366
- [x] Kubernetes 1.26: https://github.com/kubernetes/kubernetes/pull/119367
- [x] Kubernetes 1.25: https://github.com/kubernetes/kubernetes/pull/119368
- [x] Kubernetes 1.24: https://github.com/kubernetes/kubernetes/pull/119369

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/119371

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/3158

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/3158

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/30114

### Follow-up items

- [x] Ensure the Golang issue template is updated with any new requirements

/assign
cc: @kubernetes/release-engineering

**Comment by xmudrii** [comment]
Update is done.
/close
