### ISSUE TITLE
Dependency update - Golang 1.20.7

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#3181]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/3148

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/7b0c3Z5Ko8g/m/VoDsuTnYAAAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1690462737351719

### Work items

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/3189

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5679

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/3189

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5680

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/3189

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5681

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): [https://github.com/kubernetes/kubernetes/pull/119804](https://github.com/kubernetes/kubernetes/pull/119804)

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image
  - [x] `.go-version` file

> **Note**
> This update may require an update to go.sum files, for example: https://github.com/kubernetes/kubernetes/pull/118507
> This will require an API Review approval.

#### After go-runner image promotion

- [x] `distroless-iptables` image update:  https://github.com/kubernetes/release/pull/3197

  
  - [x] image promotion:  https://github.com/kubernetes/k8s.io/pull/5694

#### After distroless-iptables image promotion

- [x] kubernetes/kubernetes update (`master`):  https://github.com/kubernetes/kubernetes/pull/119818

  Ensure the following have been updated within the PR:

  - [x] distroless-iptables image
  - [x] test image

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` image update:  https://github.com/kubernetes/release/pull/3199

- [x] `k8s-ci-builder` image variants update:  https://github.com/kubernetes/release/pull/3199

### Cherry picks

 
- [x] Kubernetes 1.27: https://github.com/kubernetes/kubernetes/pull/119828
- [x] Kubernetes 1.26: https://github.com/kubernetes/kubernetes/pull/119830
- [x] Kubernetes 1.25: https://github.com/kubernetes/kubernetes/pull/119836
- [x] Kubernetes 1.24: https://github.com/kubernetes/kubernetes/pull/119837

- [x] publishing bot rule updates for active Golang versions:  https://github.com/kubernetes/kubernetes/pull/119847
- [x] publishing bot rule updates for active Golang versions(1.24 only) https://github.com/kubernetes/kubernetes/pull/119875

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/3201

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/3201

- [x] `kubekins`/`krte` image variants update:  https://github.com/kubernetes/test-infra/pull/30342

### Follow-up items

- [ ] Follow up on update of `protoc` and make cross image/builder images able to specify per-version
 

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] Update `x/net/html` in k/k (https://groups.google.com/g/golang-announce/c/qB2Cuod1A14/m/Ou23Ru0uAQAJ)

/assign
cc: @kubernetes/release-engineering

**Comment by xmudrii** [comment]
@jeremyrickard will take over
/unassign
/assign @jeremyrickard

**Comment by cpanato** [comment]
i think this can be closed
cc @xmudrii @jeremyrickard
