### ISSUE TITLE
Dependency update - Golang 1.21.1/1.20.8

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#3242]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/3181

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/UXJQvKffcao/m/3yTGjzoQAAAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1693528258265679

### Work items

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/3253

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5809

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/3253

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5808 / https://github.com/kubernetes/k8s.io/pull/5810

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/3253

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5807

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/120493

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image
  - [x] `.go-version` file

> **Note**
> This update may require an update to go.sum files, for example: https://github.com/kubernetes/kubernetes/pull/118507
> This will require an API Review approval.

#### After go-runner image promotion

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/3258

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/5819

#### After distroless-iptables image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/120527

  Ensure the following have been updated within the PR:

  - [x] distroless-iptables image
  - [x] test image

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/3257

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/3257

### Cherry picks

- [x] Kubernetes 1.25: https://github.com/kubernetes/kubernetes/pull/120497
- [x] Kubernetes 1.26: https://github.com/kubernetes/kubernetes/pull/120496
- [x] Kubernetes 1.27: https://github.com/kubernetes/kubernetes/pull/120494
- [x] Kubernetes 1.28: https://github.com/kubernetes/kubernetes/pull/120495

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/120526

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/3259

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/3259

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/30657

### Follow-up items

- [x] Ensure the Golang issue template is updated with any new requirements
- [x] <Any other follow up items>

/assign
cc: @kubernetes/release-engineering

**Comment by cpanato** [comment]
all work is done
/close
