### ISSUE TITLE
Deprecate and remove everything related to `kubepkg` (and `rapture`)

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#3265]
The kubepkg code, jobs as well as the rapture script should be considered as deprecated with the [announcement of freezing Kubernetes Legacy Package Repositories](https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/).

This issue tracks the work behind that effort.

```[tasklist]
### Tasks
- [x] Announce the cleanup on k-dev: https://groups.google.com/a/kubernetes.io/g/dev/c/xyuwDxjRcdA/m/VUGbs14KBgAJ
- [ ] https://github.com/kubernetes/test-infra/pull/30995
- [ ] https://github.com/kubernetes/release/pull/3313
- [ ] https://github.com/kubernetes/website/pull/43408
- [ ] https://github.com/kubernetes/sig-release/pull/2354
- [ ] https://github.com/kubernetes/website/pull/43409
- [ ] https://github.com/kubernetes/website/pull/43407
```

**Comment by saschagrunert** [comment]
Continuing the work.

**Comment by saschagrunert** [comment]
We're done, cannot find anything related to rapture or kubepkg any more in our repositories.

**Comment by xmudrii** [comment]
@saschagrunert Should we send an update to the mailing list that this is now done?

**Comment by saschagrunert** [comment]
@xmudrii done https://groups.google.com/g/kubernetes-sig-release/c/jhpoJ1t0fDo/m/bvrbApUODQAJ
