### ISSUE TITLE
Dependency update - Golang 1.22.0

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/release#3280]
## Note

The go1.22 set of releases aren't out yet! This is just a placeholder issue so that we can start tracking PRs that help prepare Kubernetes for go1.22.

### Tracking info

Link to any previous tracking issue: 

Golang mailing list announcement: 

SIG Release Slack thread: 

### Work items

- [ ] `kube-cross` image update: 

  
  - [ ] image promotion: 

- [ ] `go-runner` image update: 

  
  - [ ] image promotion: 

- [ ] `releng-ci` image update: 

  
  - [ ] image promotion: 

#### After kube-cross image promotion

- [ ] kubernetes/kubernetes update (`master`): 

  Ensure the following have been updated within the PR:

  - [ ] kube-cross image
  - [ ] go-runner image
  - [ ] publishing bot rules
  - [ ] test image
  - [ ] `.go-version` file

> **Note**
> This update may require an update to go.sum files, for example: https://github.com/kubernetes/kubernetes/pull/118507
> This will require an API Review approval.

#### After go-runner image promotion

- [ ] `distroless-iptables` image update: 

  
  - [ ] image promotion: 

#### After distroless-iptables image promotion

- [ ] kubernetes/kubernetes update (`master`): 

  Ensure the following have been updated within the PR:

  - [ ] distroless-iptables image
  - [ ] test image

#### After kubernetes/kubernetes (master) has been updated

- [ ] `k8s-cloud-builder` image update: 

- [ ] `k8s-ci-builder` image variants update: 

### Cherry picks

- [ ] Kubernetes x.y-1: 
- [ ] Kubernetes x.y-2: 
- [ ] Kubernetes x.y-3: 

- [ ] publishing bot rule updates for active Golang versions: 

#### After kubernetes/kubernetes (release branches) has been updated

- [ ] `k8s-cloud-builder` image update: 

- [ ] `k8s-ci-builder` image variants update: 

- [ ] `kubekins`/`krte` image variants update: 

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

cc: @kubernetes/release-engineering
cc: @liggitt

**Comment by MadhavJivrajani** [comment]
Tracking PRs related to go1.22 that we would need to pick to release branches as part of an eventual update to go1.22:

- https://github.com/kubernetes/kubernetes/pull/120750
  - 1.28:
  - 1.27: 
  - 1.26: Unlikely to be on go1.22 (EoL of 1.26 is around the same time of release of go1.22)
  - 1.25: Will be EoL
  - 1.24: EoL
---

Tracking verification of [conditions](https://github.com/kubernetes/enhancements/tree/master/keps/sig-release/3744-stay-on-supported-go-versions#proposal) for bumping go1.21 on release branches:
- [ ] ~TBD: 3 months after go 1.22 release (ETA Feb 2024)
- [ ] ~TBD: 1 month after Kubernetes 1.X release on go1.22 (ETA TBD)
- [ ] no regressions relative to go 1.20 known to impact Kubernetes
- [ ] pass unit and integration tests with both go 1.22 and the original go version for the release branch
  - [ ] 1.26: 
  - [ ] 1.27: 
  - [ ] 1.28: 
- [ ] any behavior changes in go 1.22 are mitigated to preserve existing behavior without requiring action by Kubernetes end-users
  - [ ] 1.26: 
  - [ ] 1.27: 
  - [ ] 1.28: 

---

Tracking the PR that actually bumps to go1.22:
- [ ] 
  - [ ] 1.26: 
  - [ ] 1.27: 
  - [ ] 1.28:

**Comment by pohly** [comment]
https://github.com/kubernetes/kubernetes/pull/120750 is getting cherry-picked in:
- 1.29: not needed (was included)
- 1.28: https://github.com/kubernetes/kubernetes/pull/122580
- 1.27: https://github.com/kubernetes/kubernetes/pull/122581

**Comment by cpanato** [comment]
/assign
i will work on the release engineering side, image bumps and other things :)

**Comment by cpanato** [comment]
maybe we can close this issue and open a new one to track https://github.com/kubernetes/release/issues/3280#issuecomment-1726964825

wdyt? @liggitt @MadhavJivrajani

**Comment by MadhavJivrajani** [comment]
@cpanato I'm not sure I fully understand why we need a new issue - maybe I'm missing something?

@liggitt - tracked https://github.com/golang/go/issues/65625 as a regression, thanks!

**Comment by liggitt** [comment]
> maybe we can close this issue and open a new one to track [#3280 (comment)](https://github.com/kubernetes/release/issues/3280#issuecomment-1726964825)

I have a slight preference for keeping everything associated with the minor update in a single issue, but it *is* a little weird for an issue titled go1.22.0 to track the minor update of release branches to an eventual go1.22.x... maybe we could truncate the title to go1.22?

**Comment by cpanato** [comment]
ok not a problem, was more a suggestion :) we keep this open

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/121476 bumped honnef.co/go/tools to v0.4.6

it turns out that release specifically contained a fix for evaluating go1.22: https://github.com/dominikh/go-tools/releases/tag/2023.1.6

please add that to the list of updates tracked in https://github.com/kubernetes/release/issues/3280#issuecomment-1726964825 needed for go1.22

**Comment by MadhavJivrajani** [comment]
@liggitt good catch! Thanks, I've tracked the PR.

**Comment by MadhavJivrajani** [comment]
@pohly FYI ^ 
We'll probably need to backport https://github.com/kubernetes/kubernetes/pull/121476 to 1.27 and 1.28

**Comment by pohly** [comment]
Do we want to backport [golangci-lint v1.55.1](https://github.com/kubernetes/kubernetes/pull/121476) or just bump up honnef.co/go/tools to v0.4.6 on older branches?

**Comment by liggitt** [comment]
not sure... maybe do an experimental PR to release-1.29 that bumps .go-version to 1.22.0 and just honnef.co/go/tools to v0.4.6 and see if CI passes? if so, maybe limit to just the honnef.co/go/tools bump?

**Comment by liggitt** [comment]
> @liggitt good catch! Thanks, I've tracked the PR.

thanks... can go ahead and mark 1.26 as not backported for all of those because it reached EOL

**Comment by pohly** [comment]
release-1.29 is already on golangci-lint v1.55.1 and thus honnef.co/go/tools v0.4.6. release-1.28 and older aren't.

When bumping only honnef.co/go/tools v0.4.6 together with `.go-version`, linting passed on
[release-1.28](https://github.com/kubernetes/kubernetes/pull/123768) and [release-1.27](https://github.com/kubernetes/kubernetes/pull/123769). Code gen wasn't happy about `.go-version` at 1.22.0, but I suppose that's separate.

Shall I turn those PRs into proper updates of honnef.co/go/tools?

**Comment by liggitt** [comment]
> Shall I turn those PRs into proper updates of honnef.co/go/tools?

yes, that would be great

**Comment by MadhavJivrajani** [comment]
Now that we are about to start the process of bumping the Go major version on release branches, we have one tracked regression that seems to affect `runc`: https://github.com/golang/go/issues/65625 

However, this issue is not a bug in Go itself but in `glibc` (specifically starting from `glibc 2.25`): https://github.com/golang/go/issues/65625#issuecomment-2036320298

There is an attempt at gracefully handing this in go, however that also does not seem to be a sustainable solution: https://go-review.googlesource.com/c/go/+/585019

The workaround here needs to be in runc itself as mentioned here: https://github.com/opencontainers/runc/issues/4233 

cc @liggitt

**Comment by MadhavJivrajani** [comment]
cc @akhilerm

**Comment by BenTheElder** [comment]
Though also we're pretty sure that bug only affects runc with nsenter, which kubelet is not doing, so as long as your runc binary is not with go 1.22 kubelet can be as far as I know.

**Comment by humblec** [comment]
> Now that we are about to start the process of bumping the Go major version on release branches, we have one tracked regression that seems to affect `runc`: [golang/go#65625](https://github.com/golang/go/issues/65625)
> 
> However, this issue is not a bug in Go itself but in `glibc` (specifically starting from `glibc 2.25`): [golang/go#65625 (comment)](https://github.com/golang/go/issues/65625#issuecomment-2036320298). However, the issue seems to be triggered in go1.22 because of it calling `pthread_getattr_np(pthread_self(), &attr)`
> 
> There is an attempt at gracefully handing this in go, however that also does not seem to be a sustainable solution: https://go-review.googlesource.com/c/go/+/585019
> 
> The workaround here needs to be in runc itself as mentioned here: [opencontainers/runc#4233](https://github.com/opencontainers/runc/issues/4233)
> 
> cc @liggitt

The GO cherry-pick has been approved https://github.com/golang/go/issues/67650 and mostly its going to be part of Go `1.22.4`.

**Comment by MadhavJivrajani** [comment]
I see am incoming Go CVE: https://github.com/golang/go/issues/67682

Which means go1.22.4 might come sooner than expected. @dims / @liggitt thoughts on waiting it out? The other alternative is we can bump release branches to go1.22.3 since the regression does not affect K8s itself. We would however have to be on a differing Go version than runc for at least one patch release, which could be acceptable.

**Comment by humblec** [comment]
> I see am incoming Go CVE: [golang/go#67682](https://github.com/golang/go/issues/67682)
> 
> Which means go1.22.4 might come sooner than expected. @dims / @liggitt thoughts on waiting it out? The other alternative is we can bump release branches to go1.22.3 since the regression does not affect K8s itself. We would however have to be on a differing Go version than runc for at least one patch release, which could be acceptable.

@MadhavJivrajani imo, considering a CVE fix is also part of 1.22.4, I think it's good to bump k/k on 1.22.4.

**Comment by dims** [comment]
> The other alternative is we can bump release branches to go1.22.3 since the regression does not affect K8s itself.

My vote is to keep the wheels turning as we may catch things in CI jobs from what we have now. `differing Go version than runc` is not a concern i have.

**Comment by BenTheElder** [comment]
+1 @dims, we're often having a different version anyhow when we're using prebuilt upstream binaries versus our source builds ...

Unless we know that the packages kubelet uses are not supported on the go version, this should be fine.

We continue, I think we only have the codegen issue which only applies to older branches when the go image isn't also updated?

**Comment by MadhavJivrajani** [comment]
@dims @BenTheElder go1.22.4 is slated for Tuesday (4th June): https://groups.google.com/d/msgid/golang-dev/hro34FA2QbSJZ-wwA7vkTQ%40geopod-ismtpd-25?utm_medium=email&utm_source=footer

Considering we've already kicked off testing with 1.22.3 and that hasn't surfaced failing jobs (except the codegen issue), I do think 4th June is reasonable to wait for. Please lmk if you have concerns with this and I can start working towards bumping to go1.22.3. Thanks!

**Comment by dims** [comment]
@MadhavJivrajani personally i like getting things in and watch the periodic ci jobs over the weekend when there is not that much activity and then come monday there is a set of things to do .. but it's your call :) i am ok either way in this instance.

**Comment by dims** [comment]
@MadhavJivrajani are we done here?

**Comment by cpanato** [comment]
i will build the images for the release branches :)

**Comment by cpanato** [comment]
all done :) 
/close

**Comment by MadhavJivrajani** [comment]
Yay! 🎉 
Thanks folks!
