### ISSUE TITLE
Dependency update - Golang 1.21.4 and 1.20.11

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#3347]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/3311

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/4tU8LZfBFkY/m/d-jSKR_jBwAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1699384473457839

### Work items

- [x] `kube-cross` image update: https://github.com/kubernetes/release/pull/3348

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/6060

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/3348

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/6058

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/3348

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/6059

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/121808

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image
  - [x] `.go-version` file

> **Note**
> This update may require an update to go.sum files, for example: https://github.com/kubernetes/kubernetes/pull/118507
> This will require an API Review approval.

#### After go-runner image promotion

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/3350

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/6077

#### After distroless-iptables image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/121871

  Ensure the following have been updated within the PR:

  - [x] distroless-iptables image
  - [x] test image

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/3356

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/3356

### Cherry picks

- [x] Kubernetes 1.26: https://github.com/kubernetes/kubernetes/pull/121810
- [x] Kubernetes 1.27: https://github.com/kubernetes/kubernetes/pull/121811
- [x] Kubernetes 1.28: https://github.com/kubernetes/kubernetes/pull/121812

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/121870

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/3356

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/3356

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/31234

### Follow-up items

- [x] Ensure the Golang issue template is updated with any new requirements

/assign
cc: @kubernetes/release-engineering

**Comment by saschagrunert** [comment]
@cpanato we had to bump the k8s-cloud-builder as well, should we add that to the template?

**Comment by cpanato** [comment]
@saschagrunert it is in the template
