### ISSUE TITLE
Dependency update - Golang 1.21.5/1.20.12

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#3383]
### Tracking info

Link to any previous tracking issue: #3347

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/TABUsV4-FiU/m/cajfhO09AgAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1701369936664499

### Work items

- [x] `kube-cross` image update:  https://github.com/kubernetes/release/pull/3388

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/6153

- [x] `go-runner` image update: https://github.com/kubernetes/release/pull/3388

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/6154

- [x] `releng-ci` image update: https://github.com/kubernetes/release/pull/3388

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/6155

#### After kube-cross image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/122201

  Ensure the following have been updated within the PR:

  - [x] kube-cross image
  - [x] go-runner image
  - [x] publishing bot rules
  - [x] test image
  - [x] `.go-version` file

> **Note**
> This update may require an update to go.sum files, for example: https://github.com/kubernetes/kubernetes/pull/118507
> This will require an API Review approval.

#### After go-runner image promotion

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/3389

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/6164

#### After distroless-iptables image promotion

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/122206

  Ensure the following have been updated within the PR:

  - [x] distroless-iptables image
  - [x] test image

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/3390

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/3390

### Cherry picks

- [x] Kubernetes 1.28: https://github.com/kubernetes/kubernetes/pull/122216
- [x] Kubernetes 1.27: https://github.com/kubernetes/kubernetes/pull/122217
- [x] Kubernetes 1.26: https://github.com/kubernetes/kubernetes/pull/122218

- [x] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/122299

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` image update: https://github.com/kubernetes/release/pull/3394

- [x] `k8s-ci-builder` image variants update: https://github.com/kubernetes/release/pull/3394

- [x] `kubekins`/`krte` image variants update (Go 1.21): https://github.com/kubernetes/test-infra/pull/31387 

- [x] `kubekins`/`krte` image variants update (Go 1.20): https://github.com/kubernetes/test-infra/pull/31398

### Follow-up items

- [x] Ensure the Golang issue template is updated with any new requirements
- [x] Drop publishing-bot rules for the release-1.25 branch: https://github.com/kubernetes/kubernetes/pull/122321

/assign
cc: @kubernetes/release-engineering

**Comment by saschagrunert** [comment]
@xmudrii is this done?

**Comment by xmudrii** [comment]
@saschagrunert I still need to update the publishing-bot rules (after the code freeze is lifted) and update the template.

**Comment by xmudrii** [comment]
I'm experimenting with other formats for the Golang update template.

-----------------

## Tracking info

Link to any previous tracking issue: #3347

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/TABUsV4-FiU/m/cajfhO09AgAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1701369936664499

## Work items

### Phase 1 — build images

```[tasklist]
### Build images
- [x] `kube-cross`, `go-runner`, and `releng-ci` image updates: https://github.com/kubernetes/release/pull/3388
```

```[tasklist]
### Promote images
- [x] `kube-cross` image promotion: https://github.com/kubernetes/k8s.io/pull/6153
- [x] `go-runner` image promotion: https://github.com/kubernetes/k8s.io/pull/6154
- [x] `releng-ci` image promotion: https://github.com/kubernetes/k8s.io/pull/6155
```

### Phase 2 (after `go-runner` promotion) — build `distroless-iptables` image

```[tasklist]
- [x] `distroless-iptables` image updates: https://github.com/kubernetes/release/pull/3389
- [x] `distroless-iptables` image promotion: https://github.com/kubernetes/k8s.io/pull/6164
```

### Phase 3 (after `distroless-iptables` promotion) — update `kubernetes/kubernetes` (`master`)

```[tasklist]
- [x] Update `kubernetes/kubernetes` (`master`): https://github.com/kubernetes/kubernetes/pull/122201
```

```[tasklist]
### `kubernetes/kubernetes` update checklist
- [x] Updated `.go-version` file
- [x] Updated kube-cross image
- [x] Updated go-runner image
- [x] Updated distroless-iptables image
- [x] Updated test image
- [x] Updated publishing-bot rules for `master`
```

> **Note**
> This update may require an update to go.sum files, for example: https://github.com/kubernetes/kubernetes/pull/118507
> This will require an API Review approval.

### Phase 4 (after `kubernetes/kubernetes` `master` update) — builder images

```[tasklist]
- [x] `k8s-cloud-builder` and `k8s-ci-builder` image update: https://github.com/kubernetes/release/pull/3390
- [x] `kubekins`/`krte` image update: https://github.com/kubernetes/test-infra/pull/31387 
```

## Cherry picks

### Phase 5 — create cherry-picks for release branches that use a supported Go version

```[tasklist]
- [x] Kubernetes 1.28: https://github.com/kubernetes/kubernetes/pull/122216
- [x] Kubernetes 1.27: https://github.com/kubernetes/kubernetes/pull/122217
- [x] Kubernetes 1.26: https://github.com/kubernetes/kubernetes/pull/122218
```

### Phase 6 (after mergining cherry-picks)

```[tasklist]
### Phase 6a (after mergining cherry-picks) — publishing-bot rules
- [x] Update publishing-bot rules in `kubernetes/kubernetes` for release branches: https://github.com/kubernetes/kubernetes/pull/122299
```

```[tasklist]
### Phase 6b (after mergining cherry-picks) — builder images
- [x] `k8s-cloud-builder` and `k8s-ci-builder` image update: https://github.com/kubernetes/release/pull/3394
- [x] `kubekins`/`krte` image update: https://github.com/kubernetes/test-infra/pull/31398
```

## Follow-up items



```[tasklist]
### Follow-up items
- [ ] Ensure the Golang issue template is updated with any new requirements
```

**Comment by xmudrii** [comment]
All tasks are done. :tada:
/close
