### ISSUE TITLE
Dependency update - Golang 1.21.7/1.20.14

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#3451]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/3412

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/Qdkw_yX60TE/m/no34wVjNBwAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1707291164014399

### Work items

- [x] `kube-cross`, `go-runner`, `releng-ci` image updates: https://github.com/kubernetes/release/pull/3452 / https://github.com/kubernetes/release/pull/3461

  
  - [x] `kube-cross` image promotion: https://github.com/kubernetes/k8s.io/pull/6394 / https://github.com/kubernetes/k8s.io/pull/6408

  
  - [x] `go-runner` image promotion: https://github.com/kubernetes/k8s.io/pull/6395

  
  - [x] `releng-ci` image promotion: https://github.com/kubernetes/k8s.io/pull/6396

#### After go-runner image promotion

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/3456

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/6401

#### After kube-cross and distroless-iptables image promotions

- [x] kubernetes/kubernetes update (`master`): no update on k/k main branch because that is on go1.22

### Cherry picks

- [x] Kubernetes 1.29: https://github.com/kubernetes/kubernetes/pull/123218
- [x] Kubernetes 1.28: https://github.com/kubernetes/kubernetes/pull/123228
- [x] Kubernetes 1.27: https://github.com/kubernetes/kubernetes/pull/123229
- [x] Kubernetes 1.26: https://github.com/kubernetes/kubernetes/pull/123230

- [ ] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/123235

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` and `k8s-ci-builder` image updates: https://github.com/kubernetes/release/pull/3464

- [x] `kubekins`/`krte` image updates: https://github.com/kubernetes/test-infra/pull/31948

### Follow-up items

- [x] Ensure the Golang issue template is updated with any new requirements

/assign
cc: @kubernetes/release-engineering

**Comment by liggitt** [comment]
will this be where we bump 1.26 / 1.27 / 1.28 to go 1.21?

**Comment by cpanato** [comment]
> will this be where we bump 1.26 / 1.27 / 1.28 to go 1.21?

doing those

**Comment by cpanato** [comment]
work is done here
/close
