### ISSUE TITLE
Dependency update - Golang 1.22.1/1.21.8

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#3479]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/3451

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/smSYdsWaO4o/m/7OvResZDBAAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1709244901866579

### Work items

- [ ] `kube-cross`, `go-runner`, `releng-ci` image updates: 

  
  - [ ] `kube-cross` image promotion: 

  
  - [ ] `go-runner` image promotion: 

  
  - [ ] `releng-ci` image promotion: 

#### After go-runner image promotion

- [ ] `distroless-iptables` image update: 

  
  - [ ] image promotion: 

#### After kube-cross and distroless-iptables image promotions

- [ ] kubernetes/kubernetes update (`master`): 

  Ensure the following have been updated within the PR:

  - [ ] `.go-version` file
  - [ ] kube-cross image
  - [ ] go-runner image
  - [ ] distroless-iptables image
  - [ ] publishing bot rules
  - [ ] test image

> **Note**
> This update may require an update to go.sum files, for example: https://github.com/kubernetes/kubernetes/pull/118507
> This will require an API Review approval.

#### After kubernetes/kubernetes (master) has been updated

- [ ] `k8s-cloud-builder` and `k8s-ci-builder` image updates: 

- [ ] `kubekins`/`krte` image variants update: 

### Cherry picks

- [ ] Kubernetes 1.y-1: 
- [ ] Kubernetes 1.y-2: 
- [ ] Kubernetes 1.y-3: 

- [ ] publishing bot rule updates for active Golang versions: 

#### After kubernetes/kubernetes (release branches) has been updated

- [ ] `k8s-cloud-builder` and `k8s-ci-builder` image updates: 

- [ ] `kubekins`/`krte` image updates: 

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

/assign
cc: @kubernetes/release-engineering

**Comment by xmudrii** [comment]
There's also a pre-announcement for a security release for the protobuf library which we use in several places: https://groups.google.com/g/golang-announce/c/jiGrhz7X6aU/m/I8gP6k5ABAAJ

**Comment by saschagrunert** [comment]
@cpanato looks like the image `gcr.io/k8s-staging-releng/k8s-cloud-builder:v1.30.0-go1.22.1-bullseye.0` is not available: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-fast-forward/1765641354047655936/build-log.txt

**Comment by xmudrii** [comment]
/unassign
Thank you for taking care of these updates, @cpanato!

**Comment by cpanato** [comment]
work is done
/close

**Comment by dims** [comment]
> work is done

thanks @cpanato !

/woof
