### ISSUE TITLE
Dependency update - Golang 1.23

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#3650]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/3280

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/8ciOP5ve_CM/m/fg9_BQpdFgAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1719215856518939

### Work items for go1.23.0

- [x] `kube-cross`, `go-runner`, `releng-ci` image updates: https://github.com/kubernetes/release/pull/3732

  
  - [x] `kube-cross` image promotion: https://github.com/kubernetes/k8s.io/pull/7238

  
  - [x] `go-runner` image promotion: https://github.com/kubernetes/k8s.io/pull/7239

  
  - [x] `releng-ci` image promotion: https://github.com/kubernetes/k8s.io/pull/7240

#### After go-runner image promotion

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/3736

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/7249

### Work items for go1.23rc1

- [x] `kube-cross`, `go-runner`, `releng-ci` image updates: https://github.com/kubernetes/release/pull/3669

  
  - [x] `kube-cross` image promotion: https://github.com/kubernetes/k8s.io/pull/6953

  
  - [x] `go-runner` image promotion: https://github.com/kubernetes/k8s.io/pull/6954

  
  - [x] `releng-ci` image promotion: not promoting this image 

#### After go-runner image promotion

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/3672

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/6959

### Work items for go1.23rc2

- [x] `kube-cross`, `go-runner`, `releng-ci` image updates: https://github.com/kubernetes/release/pull/3680

  
  - [x] `kube-cross` image promotion: https://github.com/kubernetes/k8s.io/pull/7023

  
  - [x] `go-runner` image promotion: https://github.com/kubernetes/k8s.io/pull/7021

  
  - [x] `releng-ci` image promotion: not promoting this image 

#### After go-runner image promotion

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/3685

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/7029

#### After kube-cross and distroless-iptables image promotions

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/126047

  Ensure the following have been updated within the PR:

  - [x] `.go-version` file
  - [x] kube-cross image
  - [x] go-runner image
  - [x] distroless-iptables image
  - [x] publishing bot rules
  - [x] test image

> **Note**
> This update may require an update to go.sum files, for example: https://github.com/kubernetes/kubernetes/pull/118507
> This will require an API Review approval.

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` and `k8s-ci-builder` image updates: https://github.com/kubernetes/release/pull/3690

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/33093

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

/assign
cc: @kubernetes/release-engineering

**Comment by MadhavJivrajani** [comment]
Tracking PRs related to go1.23 that we would need to pick to release branches as part of an eventual update to go1.23:
- https://github.com/kubernetes/kubernetes/pull/125926
  - 1.30:
  - 1.29:
  - 1.28:
---

Tracking verification of [conditions](https://github.com/kubernetes/enhancements/tree/master/keps/sig-release/3744-stay-on-supported-go-versions#proposal) for bumping go1.21 on release branches:
- [ ] TBD: 3 months after go 1.22 release (TBD)
- [ ] TBD: 1 month after Kubernetes 1.30/Kubernetes 1.31 release on go1.23 (TBD)
- [ ] no regressions relative to go 1.23 known to impact Kubernetes
  - [ ]
- [ ] pass unit and integration tests with both go 1.23 and the original go version for the release branch
  - [ ] 1.27:
  - [ ] 1.28:
  - [ ] 1.29:
- [x] any behavior changes in go 1.23 are mitigated to preserve existing behavior without requiring action by Kubernetes end-users
  - [ ] 1.28:
  - [ ] 1.29:
  - [ ] 1.30:

---

Tracking the PR that actually bumps to go1.22:
- [ ] 
  - [ ] 1.28:
  - [ ] 1.29:
  - [ ] 1.30

**Comment by cpanato** [comment]
RC2 released: https://groups.google.com/g/golang-announce/c/jW315Nz132s/m/WqkCDaiVBQAJ

**Comment by pacoxu** [comment]
https://github.com/kubernetes/release/pull/3685 post run of this PR failed:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-distroless-iptables/1813995910510678016

**Comment by liggitt** [comment]
go 1.23.0 is out now, can rebump master to 1.23 now 🎉

**Comment by cpanato** [comment]
all done

/close

**Comment by liggitt** [comment]
should we keep this open for tracking changes required for go 1.23 (like https://github.com/kubernetes/release/issues/3280#issuecomment-1726964825), and backport of 1.23 to release branches?

**Comment by liggitt** [comment]
Can we add an item to https://github.com/kubernetes/release/issues/3650#issuecomment-2211373351 to pick the `godebug default=go1.x` commit from https://github.com/kubernetes/kubernetes/pull/127271 to release branch go.mod files?

xref https://tip.golang.org/doc/godebug#default

**Comment by liggitt** [comment]
can update https://github.com/kubernetes/release/issues/3650#issuecomment-2211373351 with https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+KUBE_HACK_TOOLS_GOTOOLCHAIN+is%3Aclosed+is%3Amerged merges and picks, which picked up the https://github.com/kubernetes/kubernetes/pull/125926 and https://github.com/kubernetes/kubernetes/pull/126709 backports to 1.29

**Comment by liggitt** [comment]
Timeline and go1.23 quality-wise, I think we're ready to proceed bumping 1.29-1.31 to go 1.23

**Comment by liggitt** [comment]
PRs open to bump release branches to go 1.29 - https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr++-base%3Amaster+author%3Aliggitt+1.23.6+

still needs go-runner / builder / kube-cross images built

**Comment by cpanato** [comment]
> Timeline and go1.23 quality-wise, I think we're ready to proceed bumping 1.29-1.31 to go 1.23

I can do the bumps, please let me know

**Comment by sbueringer** [comment]
Could it be that this is done?

**Comment by cpanato** [comment]
yep

/close
