### ISSUE TITLE
Dependency update - Golang 1.22.5

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#3657]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/3628

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/zz9YfuJ6eCc/m/GtpAohutAAAJ

SIG Release Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1719510876630789

### Work items

- [x] `kube-cross`, `go-runner`, `releng-ci` image updates: https://github.com/kubernetes/release/pull/3664

  - [x] `kube-cross` image promotion:  https://github.com/kubernetes/k8s.io/pull/6933

  - [x] `go-runner` image promotion: https://github.com/kubernetes/k8s.io/pull/6936

  - [x] `releng-ci` image promotion: https://github.com/kubernetes/k8s.io/pull/6937

#### After go-runner image promotion

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/3665

  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/6938

#### After kube-cross and distroless-iptables image promotions

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/125894

  Ensure the following have been updated within the PR:

  - [x] `.go-version` file
  - [x] kube-cross image
  - [x] go-runner image
  - [x] distroless-iptables image
  - [x] publishing bot rules
  - [x] test image

> **Note**
> This update may require an update to go.sum files, for example: https://github.com/kubernetes/kubernetes/pull/118507
> This will require an API Review approval.

#### After kubernetes/kubernetes (master) has been updated

- [x] `k8s-cloud-builder` and `k8s-ci-builder` image updates: https://github.com/kubernetes/release/pull/3666

- [x] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/32909

### Cherry picks

- [x] Kubernetes 1.30: https://github.com/kubernetes/kubernetes/pull/125895
- [x] Kubernetes 1.29: https://github.com/kubernetes/kubernetes/pull/125896
- [x] Kubernetes 1.28: https://github.com/kubernetes/kubernetes/pull/125897
- [x] Kubernetes 1.27: https://github.com/kubernetes/kubernetes/pull/125898

- [ ] publishing bot rule updates for active Golang versions: https://github.com/kubernetes/kubernetes/pull/125906

#### After kubernetes/kubernetes (release branches) has been updated

- [x] `k8s-cloud-builder` and `k8s-ci-builder` image updates: https://github.com/kubernetes/release/pull/3666

- [x] `kubekins`/`krte` image updates: https://github.com/kubernetes/test-infra/pull/32909

### Follow-up items

- [ ] Ensure the Golang issue template is updated with any new requirements
- [ ] <Any other follow up items>

cc: @kubernetes/release-engineering

**Comment by cpanato** [comment]
all work is done

/close
