### ISSUE TITLE
Dependency update - Golang 1.24.0

### ISSUE THREAD

**Issue by liggitt** [kubernetes/release#3772]
### Tracking info

Link to any previous tracking issue: https://github.com/kubernetes/release/issues/3650

Golang mailing list announcement: 

SIG Release Slack thread: 

### Work items for go1.24rc1

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/vYMfuq_XO6w/m/YlJ1SR6lAQAJ

- [x] `kube-cross`, `go-runner`, `releng-ci` image updates: https://github.com/kubernetes/release/pull/3872

  
  - [x] `kube-cross` image promotion: https://github.com/kubernetes/k8s.io/pull/7674

  
  - [x] `go-runner` image promotion: https://github.com/kubernetes/k8s.io/pull/7675

  
  - [x] `releng-ci` image promotion: not promoting this image 

#### After go-runner image promotion

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/3884

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/7687

### Work items for go1.24rc2

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/L8jWYHEfOlQ

- [x] `kube-cross`, `go-runner`, `releng-ci` image updates: https://github.com/kubernetes/release/pull/3904

  
  - [x] `kube-cross` image promotion: https://github.com/kubernetes/k8s.io/pull/7756

  
  - [x] `go-runner` image promotion: https://github.com/kubernetes/k8s.io/pull/7755

  
  - [x] `releng-ci` image promotion: not promoting this image 

#### After go-runner image promotion

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/3910

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/7765

### Work items for go1.24rc3

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/w2gBC3sJibs/m/bUz6JjCCAAAJ

- [x] `kube-cross`, `go-runner`, `releng-ci` image updates: https://github.com/kubernetes/release/pull/3911

  
  - [x] `kube-cross` image promotion: https://github.com/kubernetes/k8s.io/pull/7768

  
  - [x] `go-runner` image promotion:  https://github.com/kubernetes/k8s.io/pull/7769

  
  - [x] `releng-ci` image promotion: not promoting this image 

#### After go-runner image promotion

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/3918

  
  - [x] image promotion:  https://github.com/kubernetes/k8s.io/pull/7773

### Work items for go1.24

Golang mailing list announcement: https://groups.google.com/g/golang-announce/c/_G2hEiKx8SE/m/5uEc3vwVAgAJ

- [x] `kube-cross`, `go-runner`, `releng-ci` image updates: https://github.com/kubernetes/release/pull/3930

  
  - [x] `kube-cross` image promotion: https://github.com/kubernetes/k8s.io/pull/7811

  
  - [x] `go-runner` image promotion: https://github.com/kubernetes/k8s.io/pull/7813

  
  - [x] `releng-ci` image promotion: https://github.com/kubernetes/k8s.io/pull/7814

#### After go-runner image promotion

- [x] `distroless-iptables` image update: https://github.com/kubernetes/release/pull/3932

  
  - [x] image promotion: https://github.com/kubernetes/k8s.io/pull/7815

#### After kube-cross and distroless-iptables image promotions

- [x] kubernetes/kubernetes update (`master`): https://github.com/kubernetes/kubernetes/pull/129688

  Ensure the following have been updated within the PR:

  - [x] `.go-version` file
  - [x] kube-cross image
  - [x] go-runner image
  - [x] distroless-iptables image
  - [x] publishing bot rules
  - [x] test image

> **Note**
> This update may require an update to go.sum files, for example: https://github.com/kubernetes/kubernetes/pull/118507
> This will require an API Review approval.

#### After kubernetes/kubernetes (master) has been updated

- [ ] `k8s-cloud-builder` and `k8s-ci-builder` image updates: https://github.com/kubernetes/release/pull/3942

- [ ] `kubekins`/`krte` image variants update: https://github.com/kubernetes/test-infra/pull/34425

### Follow-up items

- [x] Ensure the Golang issue template is updated with any new requirements

/assign
cc: @kubernetes/release-engineering

**Comment by liggitt** [comment]
Tracking PRs related to go1.24 that we would need to pick to release branches as part of an eventual update to go1.24:

- https://github.com/kubernetes/kubernetes/pull/127422
  - 1.32: https://github.com/kubernetes/kubernetes/pull/127422
  - 1.31: https://github.com/kubernetes/kubernetes/pull/129519
  - 1.30: https://github.com/kubernetes/kubernetes/pull/129521
  - 1.29: https://github.com/kubernetes/kubernetes/pull/129524
  - 1.28: EoL

- https://github.com/kubernetes/kubernetes/pull/129430
  - 1.32: https://github.com/kubernetes/kubernetes/pull/129495
  - 1.31: https://github.com/kubernetes/kubernetes/pull/129494
  - 1.30: https://github.com/kubernetes/kubernetes/pull/129493
  - 1.29: https://github.com/kubernetes/kubernetes/pull/129492
  - 1.28: EoL

- https://github.com/kubernetes/kubernetes/pull/129688 (only the `Bump hack/tools to github.com/golangci/golangci-lint 1.64.5 for go 1.24` and `golangci-lint: temporarily suppress known issues in the code base` commits)
  - 1.32: https://github.com/kubernetes/kubernetes/pull/134593
  - 1.31: https://github.com/kubernetes/kubernetes/pull/134594
  - 1.30: EOL 
  - 1.29: EOL

- https://github.com/kubernetes/kubernetes/pull/134588
  - 1.34: https://github.com/kubernetes/kubernetes/pull/134589
  - 1.33: https://github.com/kubernetes/kubernetes/pull/134590
  - 1.32: https://github.com/kubernetes/kubernetes/pull/134591
  - 1.31: https://github.com/kubernetes/kubernetes/pull/134592


---

Tracking verification of [conditions](https://github.com/kubernetes/enhancements/tree/master/keps/sig-release/3744-stay-on-supported-go-versions#proposal) for bumping go1.21 on release branches:
- [x] ~2025-05: 3 months after go 1.24 release (ETA 2025-02)
- [x] ~2025-05: 1 month after Kubernetes 1.33 release on go1.24 (ETA 2025-04-15)
- [x] no regressions relative to go 1.24 known to impact Kubernetes
- [x] pass unit and integration tests with both go 1.24 and the original go version for the release branch
  - [x] 1.32: https://github.com/kubernetes/kubernetes/pull/134617
  - [x] 1.31: https://github.com/kubernetes/kubernetes/pull/134618
  - ~1.30: EOL~
  - ~1.29: EOL~
- [x] any behavior changes in go 1.24 are mitigated to preserve existing behavior without requiring action by Kubernetes end-users

---

Tracking the PR that actually bumps to go1.24:
- [x] 1.32: https://github.com/kubernetes/kubernetes/pull/134617
- [x] 1.31: https://github.com/kubernetes/kubernetes/pull/134618

**Comment by cpanato** [comment]
work for go1.24 in the main (master) branch is done 
will keep this issue open for when we move to the other active release branches

**Comment by xmudrii** [comment]
Release branches are not yet updated
/remove-lifecycle stale

**Comment by liggitt** [comment]
it looks like we never bumped release branches to go 1.24

* https://github.com/kubernetes/kubernetes/blob/release-1.32/.go-version
* https://github.com/kubernetes/kubernetes/blob/release-1.31/.go-version
