### ISSUE TITLE
[Umbrella] Automate updates to k-sigs/release-notes

### ISSUE THREAD

**Issue by jeefy** [kubernetes/release#834]
This outlines the primary efforts identified to get the ball rolling in automating updates to the release notes website. Doing this will ensure timely updates to relnotes.k8s.io and removes the human bottleneck. :) Yay!

- [ ] Update the `release-notes` golang tool to automatically create a PR against the k-sigs/relnotes repo. 
  This is going to be the majority of effort, and some sane defaults will need to be put in place to handle things like checking for a fork of the repo. 
- [ ] Update the `relnotes` bash script to, instead, generate/include a link to relnotes.k8s.io for the specific release
- [ ] Propose and change cadence of "weekly release notes updates" to match the alpha/beta/RC cuts.
- [ ] Document (within the Release Team handbook) policy around handling alpha/beta/RC PRs to k-sigs/release-notes (For the release team updates, link to the PR's preview site)

/assign @onyiny-ang @saschagrunert 
/priority important-soon
/sig release
/area release-eng
/cc

**Comment by jeefy** [comment]
@onyiny-ang @saschagrunert If I missed anything let me know and I'll update this. :)

**Comment by saschagrunert** [comment]
@paulbouwer, @kcmartin @cartyc let's follow up and check how we could start working on this. 

From the website point of view I started proposing a PR today which should give us the ability to hide unpublished releases.
https://github.com/kubernetes-sigs/release-notes/pull/83

**Comment by saschagrunert** [comment]
Hey, I'm now moving forward with this, so there are three automation enhancements ready for review: 
- https://github.com/kubernetes/release/pull/875
- https://github.com/kubernetes/release/pull/879
- https://github.com/kubernetes/release/pull/880

If we can get these in I can continue with the PR creation automation.

**Comment by markyjackson-taulia** [comment]
/remove-lifecycle stale
Going to keep this open as I think it is worthy

**Comment by puerco** [comment]
/remove-lifecycle stale
This is now in krel but we are actively working on it

**Comment by saschagrunert** [comment]
Most of the mentioned enhancements are now in place, whereas the relnotes bash script does not exist any more. We have additional improvements planned which can be tracked in other issues.

Let’s 🙂
/close
