### ISSUE TITLE
Establish Kubernetes build/stage/release process on k8s-infra

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#911]
### Build
- [x] Enable Kubernetes build on k8s-infra via Prow
  - [x] (https://github.com/kubernetes/release/pull/900) Add support for running Kubernetes builds via Google Cloud Build
  - [x] (https://github.com/kubernetes/test-infra/pull/14747) Allow GCB builds from arbitrary build directories
  - [x] (https://github.com/kubernetes/test-infra/pull/14773) Add shadow kubernetes build jobs
  - [x] (https://github.com/kubernetes/test-infra/pull/14788) Configure kubernetes-build prototype jobs to use the GCB builder
  - [ ] Migrate `ci-kubernetes-build*` jobs to use k8s-infra once stage/release components are in place

### Stage/Release - Phase 0 - Staging only

- [x] Create feature branch (`prototype`) for initial stage/release prototype on k8s-infra
- [x] (#909) Initial stage/release prototype on k8s-infra
- [x] (https://github.com/kubernetes/k8s.io/pull/434) Create `release-managers-admins@` to grant elevated privileges to GCP for SIG Release Chairs
- [x] (https://github.com/kubernetes/k8s.io/pull/434) Grant GCP KMS access to SIG Release Chairs
- [x] (https://github.com/kubernetes/k8s.io/pull/434) Enable KMS API for SIG Release GCP projects
- [x] Configure KMS secret to store `k8s-release-robot` GitHub token
- [x] (#909) Update build and release GCB configs to include GitHub token
- [ ] Configure staging job on Prow against `prototype` branch 
- [x] Create Editor/Viewer roles for Patch Release, Branch Mgmt, and Release Manager Associates

### Stage/Release - Phase 1 - Prod test

- [x] (https://github.com/kubernetes/k8s.io/pull/641) Enable KMS API for release staging projects
- [x] (https://github.com/kubernetes/release/pull/1163) Move KMS keys to k8s-releng-prod GCP project
- [x] (https://github.com/kubernetes/k8s.io/pull/641) Configure staging service account with access to copy GCS objects into prod test account
- [ ] (https://github.com/kubernetes/release/pull/957) Configure nomock stage/release jobs to write to prod test GCS buckets
- [ ] Permissions audit and reconciliation between prod test and prod
- [ ] Deprecate `k8s-staging-release-test` and `k8s-infra-sig-release-prototype` GCP projects - #1161

### Stage/Release - Phase 3 - `dl.k8s.io` cutover

/assign
/priority important-soon
/milestone v1.19
/kind feature

**Comment by justaugustus** [comment]
@dims, @thockin, @cblecker, @listx -- this is primarily a braindump/aggregation of the work I've done thus far. Can you give me a gut-check on the order of operations / missing steps from the k8s-infra side?

**Comment by justaugustus** [comment]
FYI @kubernetes/release-engineering @kubernetes/k8s-infra-team

**Comment by justaugustus** [comment]
cc: @dims @bartsmykla

**Comment by bartsmykla** [comment]
@justaugustus I'm gonna add this topic to this week's k8s-infra-wg call, because the process should be straight forward but I'm not sure which cluster we should use to whole buiold/stage/release process.

cc. @dims @thockin

**Comment by justaugustus** [comment]
@bartsmykla -- I won't be available this week for discuss. 
Can you add it to the Release Engineering agenda for next week and few of you can come to our meeting instead?

Staging and releasing happens via GCB, so I'm not sure that we'll need a cluster for that, btw.

**Comment by bartsmykla** [comment]
@justaugustus sure, let's meet and discuss it during the Release Engineering meeting.

**Comment by bartsmykla** [comment]
@justaugustus do you want to discuss it at the next SIG Release meeting (I think it's the next week) or Release Engineering one (I think it's in the next two weeks)?

**Comment by bartsmykla** [comment]
@justaugustus ping

**Comment by justaugustus** [comment]
@bartsmykla -- yep. Drop it on the agenda for next week's SIG Release meeting. :)

**Comment by bartsmykla** [comment]
Done

**Comment by saschagrunert** [comment]
Closing as resolved, the build/stage/release process on k8s-infra has been established.
